### ISSUE TITLE
Auth server could not shutdown gracefully: context deadline exceeded

### ISSUE THREAD

**Issue by wtrdk** [gphotosuploader/gphotos-uploader-cli#100]
I've been using this tool for a few days now, backing up a lot of photos. Since this morning I get this error message:
```Auth server could not shutdown gracefully: context deadline exceeded```
Followed by:
```failed uploading image: failed uploading image: status message should be OK/Succecc, found: Failed: There was an error while trying to create this media item.```

The error appears at uploading a random photo. If I run it again, it might upload the photo that seemed to cause the error before, and throw this error at a different photo. After running again, it uploads some photo's (like 5 or so) and then it throws this error again.

Does anyone know what might cause this problem?

I'm using the latest homebrew version on MacOS (MacBook Pro)

**Comment by pacoorozco** [comment]
Hi @wtrdk 

I think it's solved from the #107 PR. Can you confirm it?

**Comment by pacoorozco** [comment]
I'm closing this issue @wtrdk. If the problem persist, feel free to re-open it.
