### ISSUE TITLE
Lose auth token after an hour

### ISSUE THREAD

**Issue by avidrissman** [gphotosuploader/gphotos-uploader-cli#103]
(FYI this is an upstreaming of https://github.com/rfgamaral/docker-gphotos-uploader/issues/8)

Repro:
1. Download the [latest release](https://github.com/nmrshll/gphotos-uploader-cli/releases) of `gphotos-uploader-cli`.
1. Run `gphotos-uploader-cli init` and change the `config.hjson` with your credentials and e-mail. `SecretsBackendType` can be set to `auto` or `file`; it doesn’t matter.
1. Run `gphotos-uploader-cli` as much as you want in a 10-minute span. Except for prompting for a key for local encryption of the auth token, it works great.
1. Wait an hour.
1. Run `gphotos-uploader-cli`.

What should happen:
It should work. The auth token shouldn’t expire in an hour.

What does happen:
It doesn’t work. It says the token is invalid and kicks you back to the Google auth page. (The auth page immediate re-grants the token, but still.)

**Comment by rfgamaral** [comment]
This might be relevant: https://stackoverflow.com/questions/13851157/oauth2-and-google-api-access-token-expiration-time

**Comment by pacoorozco** [comment]
I'm afraid that `gphotos-uploader-cli` is not behaving well with Refresh token... I'm going to review the code, but I've not seen anything about it at first glance

**Comment by rfgamaral** [comment]
> 
> 
> I'm afraid that `gphotos-uploader-cli` is not behaving well with Refresh token... I'm going to review the code, but I've not seen anything about it at first glance

I'd love to take a look but I'm confused by the code, can you please point me in the right direction? Which repository/files contain the code that requests the access/refresh token from the Google Photos API?

**Comment by pacoorozco** [comment]
@rfgamaral I don't understand the way it is programmed either. My idea is to make a refactor of that part of the code and make it clearer and testable.

https://github.com/nmrshll/gphotos-uploader-cli/blob/ed356cde5cd26fe39f9e5359d9df70b10a1de1a7/upload/gPhotosAuth.go#L16

**Comment by pacoorozco** [comment]
It's duplicated by #93, so I'll close it and we will continue with this one.

**Comment by pdecat** [comment]
This has resolved all issues for me: https://github.com/nmrshll/oauth2-noserver/pull/5

**Comment by pacoorozco** [comment]
See the branch `issue-103` and see if it works!!!

**Comment by rfgamaral** [comment]
> 
> 
> See the branch `issue-103` and see if it works!!!
> 
> I'm completing tests and the PR...

I wasn't able to test this because it completely breaks the implementation for my Docker container. Here's two things that could help me out:

- Make the server listen on all interfaces and not just `localhost`, or at least all internal interfaces;
- Make the server always listen on a specific port and not a random one.

I do have one additional question about this, does this make `oauth2-noserver` dependency redundant? If not, what's the role `oauth2-noserver` because it doesn't seem to be used anymore.

**Comment by schokotets** [comment]
I tried the branch `issue-103` too, but it doesn't do it for me either.
I am unable to authenticate the app, I get redirected to a 400 error page:

```
Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:<random port>, does not match the ones authorized for the OAuth client.
To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/<.... (invalid url)>
```

I have yet to try @pdecat's recommended fix

**Comment by pdecat** [comment]
@schokotets the easiest to test my fix is maybe using my branch for PR https://github.com/gphotosuploader/gphotos-uploader-cli/pull/63

It also includes this important fix: https://github.com/gphotosuploader/gphotos-uploader-cli/commit/815aba6d8352b3e0749924bb9325c46aaad94525

**Comment by schokotets** [comment]
@pdecat issuing `make build` failed with your pull request.
```
--> Building binary artifact (gphotos-uploader-cli v0.5.0 (build: a8d5d55))...
# github.com/nmrshll/gphotos-uploader-cli/upload
upload/fileUpload.go:91:19: f.client.UploadFileResumable undefined (type *"github.com/gphotosuploader/google-photos-api-client-go/lib-gphotos".Client has no field or method UploadFileResumable)
make: *** [Makefile:35: build] Error 2
```
I proceeded to manually edit `datastore/tokenstore/repository_keyring.go`, implementing your change as in the commit 815aba6. I'm now trying the upload again, will update. A positive I noticed was that I wasn't prompted again - unneccesarily - for a new keyring password.

**Comment by pdecat** [comment]
I did a quick rebase from my phone that must have broken something, sorry. Can't fix right now...

**Comment by rfgamaral** [comment]
@pdecat Would it be possible for you to isolate both changes? It makes it harder to debug problems when multiple changes are added when testing just one thing.

**Comment by pdecat** [comment]
@rfgamaral sure, will do next week.

**Comment by pdecat** [comment]
@schokotets just tested my branch, works fine. Did you update go.mod too?

**Comment by schokotets** [comment]
Update! Solely implementing 815aba6 didn't do the magic for me. Uploading over the course of multiple hours finally worked when I implemented nmrshll/oauth2-noserver#5.

**Comment by pdecat** [comment]
Submitted #107

**Comment by pacoorozco** [comment]
Hi,

> * Make the server listen on all interfaces and not just `localhost`, or at least all internal interfaces;

The new package doesn't allow to use any other interface different from `localhost`. I need to look for a new one or using https://github.com/nmrshll/oauth2-noserver/pull/5.

Paco

**Comment by rfgamaral** [comment]
Are you sure? That's really weird... There's usually always that option.

Well, just to be clear, your current implementation in `issue-103`, completely prevents me from using this project in my Docker container.

If you're still Keen in going forward with they (as oppposed to other alternatives), can you at least force a fixed port instead of a random one?

**Comment by pacoorozco** [comment]
Hi @rfgamaral 

I've been reviewing your cde, and as far as I see here: https://github.com/rfgamaral/docker-gphotos-uploader/blob/master/rootfs/usr/local/bin/oauth.sh you don't need to neither use all interfaces nor a fixed port. You are running `curl` inside the docker... Am I right?

> Well, just to be clear, your current implementation in issue-103, completely prevents me from using this project in my Docker container.

Yes, I was not thinking in this use case, but port could be set

**Comment by pacoorozco** [comment]
Can we move this forward and think in future implementations later? 

I'll try to maintain your current auth mechanism in order to not break any change is your side.... What do you think? @rfgamaral

**Comment by rfgamaral** [comment]
> Can we move this forward and think in future implementations later?

I'm not sure what you mean...

**Comment by pacoorozco** [comment]
@rfgamaral as far as I know current implementation in `issue-103` branch will solve the refresh token problem and it's compatible with your current auth method...  So **I propose to merge it now**, in the future, if you need other auth mechanism, we can add modifications to the current implementation.

**Comment by rfgamaral** [comment]
> @rfgamaral as far as I know current implementation in `issue-103` branch will solve the refresh token problem and it's compatible with your current auth method... So **I propose to merge it now**, in the future, if you need other auth mechanism, we can add modifications to the current implementation.

The current approach prints a public URL on the console that a user needs to open in order to authenticate itself. The current approach posta a "localhost" URL and this URL is only visible inside the container, thus breaking my current auth method. It's not compatible at all.
