### ISSUE TITLE
Change how --config flag is working

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#104]
Currently you can use `--config` flag to set the **config file path**. But there is no option to change the place where completed uploads database is storing the upload files or where secrets backend is keeping the credentials.

If you use `--config /home/user/my_config/config.hjson`:
```
/home/user/my_config
|-- config.hjson (file)
|
.config/gphotos-uploader-cli
|-- uploads.db (folder)
|-- secrets (folder)
```

This makes `--config` flag useless for:

* Mounting all configuration files inside a mounted volume in a docker.
* Using completed uploads database for different accounts. Currently the database is the same for all the accounts, and it would be interesting to maintain different one per account.
* Havng configuration files per environment. Let's imagine you want to have different PRE/PRO env.

**Describe the solution you'd like**
I would like to change `--config` to set the **folder** where all these configuration is kept. 

If you use `--config /home/user/my_config`:
```
/home/user/my_config
|-- config.hjson (file)
|-- uploads.db (folder)
|-- secrets (folder)
```
and by default (if you don't set any config file `~/.config/gphotos-uploader-cli` will be used:
```
.config/gphotos-uploader-cli
|-- config.hjson (file)
|-- uploads.db (folder)
|-- secrets (folder)
```

You will be able to use `--config` or `GPHOTOS_UPLOADER_CONFIG_DIR` environment variable to set configuration folder. `--config` will override environment variable. **WDYT?**

Thanks @rfgamaral for raising it up

**Comment by rfgamaral** [comment]
Looks good to me 🙂
