### ISSUE TITLE
Failed: There was an error while trying to create this media item.

### ISSUE THREAD

**Issue by Tra2x** [gphotosuploader/gphotos-uploader-cli#105]
**Describe the bug**
I used this tool now since 3 days. The first day was perfect and I uploaded about 20GB of media from my NAS over the raspberry. Meanwhile I get many times after some short time "Failed: There was an error while trying to create this media item." Then the program stops.
When restarting the upload from the picture is working fine and on of the next is not working.

**To Reproduce**
In thought it's a problem, when uploading an already existing photo. But the problem occure randomly

**Detailed Information**
I'm pretty new in go and the google api and also my programming skills are very limited, nevertheless I tried to analyse the problem. Therefore I made some modifications on go/pkg/mod/github.com/gphotosuploader/google-photos-api-client-go@v1.0.1/lib-gphotos/client.go
```
result := batchResponse.NewMediaItemResults[0]
  if result.Status.Message != "OK" && result.Status.Message != "Success" {
    if result.Status.Code == 13 {
      // TODO: We should use a different field like googleapi.ServerResponse
      log.Printf("Data Result: %+v\n", result)
      log.Printf("Data Result.Status : %+v\n\n\n\n", result.Status)
      //return nil, stacktrace.NewError("status message should be OK/Succecc, found: %s", result.Status.Message)
      retry = true
      continue
    }
    log.Printf("status message should be OK/Succecc, found: %s\n\n\n", result.Status.Message)
    return nil, stacktrace.NewError("status message should be OK/Succecc, found: %s", result.Status.Message)
  }else{
    log.Printf("%s uploaded successfully as %s", filename, result.MediaItem.Id)  
  }
```

With the following result : 
```
2019/08/06 15:09:33 Data Result: &{MediaItem:<nil> Status:0xc00014f6e0 UploadToken:XXX ForceSendFields:[] NullFields:[]}
2019/08/06 15:09:33 Data Result.Status : &{Code:13 Details:[] Message:Failed: There was an error while trying to create this media item. ForceSendFields:[] NullFields:[]}
```

**Desktop (please complete the following information):**
 - I use a raspberry Pi with rasbian

As far as I understood 13 is a internal error from google.
Does somebody has any Idea what I can further do?

Thanks in advance
Markus

**Comment by Tra2x** [comment]
Hello again,
does nobody has an Idea or was my english so bad, that you couldn't understand my problem?
Anything else what I can do that you can help me? Maybe make some more analysis?
Thanks
Markus

**Comment by pacoorozco** [comment]
Hi @Tra2x 

First of all, thanks for submitting this issue. I've been reviewing the problem, and as you mentioned, Google Photos is returning an error, so `gphotos-uploader-cli` is logging it.

Besides the fact that our cli should give more context about the error (TODO item), we should test why these media items are failing. 

* Is failing randomly? Or is failing with some type of file?
* Can you give me information about the file you were uploading?
* Can you try to upload the same file twice? You should use different file names.

I will try to follow up with this issue, but bear in mind that summer holidays are in place :sweat_smile:

**Comment by Tra2x** [comment]
Hello @pacoorozco ,

thanks for your reply, it's wired, but since 3 days it's running smooth and without any problems.
As soon the problem comes back I will try to analyse it deeper.

Thanks

**Comment by pacoorozco** [comment]
After more than one week I'm going to close this issue.. If the problem persists, please create another one referring this one @Tra2x

**Comment by henry54809** [comment]
I've found the same issue to occur consistently if several workers are trying to create media items in the same photo album. Google API returns status code 409 for these scenarios. 
Running on precompiled v1.0.2 for Mac.
