### ISSUE TITLE
Help needed for running the program thoroughly

### ISSUE THREAD

**Issue by hanglearning** [gphotosuploader/gphotos-uploader-cli#108]
Hey guys, this tool looks amazing and thanks to the author for his hard work! But I could never get it to run thoroughly, so I need some help from you.

When I run the program, it seems it could upload a few files, then stops and shows me this message:

> 2019/08/09 22:54:51 failed uploading image: failed uploading image: status message should be OK/Succecc, found: Failed: There was an error while trying to create this media item.
>  --- at /home/travis/gopath/pkg/mod/github.com/gphotosuploader/google-photos-api-client-go@v1.0.1/lib-gphotos/client.go:148 (Client.UploadFile) ---

I assumed it uploaded some files because when I run the program after running it the first time it shows some images have already been uploaded like:

> 2019/08/09 22:54:49 Uploading IMG_4946.MOV
> 2019/08/09 22:54:49 already uploaded: /users/chenhang91/Archived/Pictures/072519 003126am SE/IMG_4949.MOV: skipping file...

When the program first tried to authenticate my google account, it showed an unsecured app page, and I realized that it is something I might have to set up besides creating the ClientID and ClientSecrect on the google cloud console. But to verify this app, I need to provide an url to this secure app I "created", but I don't have any. Might this be the reason that uploading failed?

Thanks!

**Comment by pacoorozco** [comment]
Hi Hang

The shared log means that this object was not uploaded properly. There
could be a lot of reasons for that ( unsupported file formats...)

Please give me more context including what file was being uploaded.

The second part... to get your client Id and secret you should go to Google
Console.  Thus is something we should document properly but I suggest you
follow @rfgamaral who has done a terrific job

https://github.com/rfgamaral/docker-gphotos-uploader

I hope it works for you.

Paco

>

**Comment by hanglearning** [comment]
Thank you very much for your prompt reply Paco! I will take a look and try to find any potential problem

**Comment by pacoorozco** [comment]
Can I close this issue @hanglearning ?

**Comment by pacoorozco** [comment]
I'm closing the issue @hanglearning. If the problem persist, feel free to open it again.
