### ISSUE TITLE
Fatal error when you try to upload something not supported

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#110]
**Describe the bug**
When you try to upload a file with a non supported format, the CLI make a fatal shutdown.

**To Reproduce**
1. Create a text file (for example) and try to upload the folder containing it.
2. See error

**Expected behavior**
It should warn that the file was not uploaded, but it should continue with the rest of files.

**Screenshots**
```
$ ./gphotos-uploader-cli
Enter passphrase to unlock ~/.config/gphotos-uploader-cli: 
2019/08/20 21:49:20 Uploading object: file=~/Flowers/kk.txt
2019/08/20 21:49:20 Uploading kk.txt
2019/08/20 21:49:20 Error during upload, sleeping for 10 seconds before retrying...
2019/08/20 21:49:31 Error during upload, sleeping for 10 seconds before retrying...
2019/08/20 21:49:41 Error during upload, sleeping for 10 seconds before retrying...
2019/08/20 21:49:51 failed uploading image: failed uploading image: failed adding media kk.txt
 --- at~/src/go/pkg/mod/github.com/gphotosuploader/google-photos-api-client-go@v1.0.1/lib-gphotos/client.go:139 (Client.UploadFile) ---
Caused by: googleapi: Error 400: Request must contain a valid upload token., badRequest
```

**Comment by phoenix1887** [comment]
Same thing happened to me with a .mp4 file it didn't like for some reason. The whole thing crashes and has to be restarted again. Fails again until you add the filename to the exclude patterns list in config file. Should be more graceful and skip file, notate in summary and continue with the rest 👍

**Comment by pacoorozco** [comment]
The problem was not upstream. It was a bad handled error response.
