### ISSUE TITLE
Can you have watch folders?

### ISSUE THREAD

**Issue by bfayers** [gphotosuploader/gphotos-uploader-cli#12]
IE: can I leave the programme running and if a new photo is put in folder can it auto upload it?

**Comment by nmrshll** [comment]
not for the moment, but I'll tag your question as a feature request.

NB: if you run windows or mac, I think Google backup and sync would do the job.

**Comment by bfayers** [comment]
@nmrshll Yep, trying to get the official windows apps features on a linux box.

Does this not upload duplicates?

**Comment by nmrshll** [comment]
It does upload any files, google handles the de-duplication on the server.

**Comment by bfayers** [comment]
@nmrshll okay, and one last question it doesn't seem I can run 
```
gphotos-uploader-cli /imageFolder/imageFilePath.jpg
```

Is there a chance of this being added, also in the config file can you tell it to upload to a pre existing album?

**Comment by nmrshll** [comment]
There is no feature at the moment for uploading to a pre-existing album, but it seems like a useful one. I'll open a separate issue for this.

For this one tough:
`gphotos-uploader-cli /imageFolder/imageFilePath.jpg` what is the thing you really want to do with this ? For one picture it seems easier to just open a web browser and drag and drop, and I want to avoid overcomplicating the uploader.

**Comment by bfayers** [comment]
@nmrshll For full context I have a camera that can upload to a SMB share and I want the camera to upload into the folder then I would chain inotifywait to see the file get dropped in place and then run this uploader to upload it

**Comment by nhorvath** [comment]
> It does upload any files, google handles the de-duplication on the server.

Keeping track of what you have uploaded and not reuploading would be a good idea, especially considering google limits to 30 uploads per minute. Subsequent runs on a large photo store are impossible.
