### ISSUE TITLE
OAuth failed

### ISSUE THREAD

**Issue by greensea** [gphotosuploader/gphotos-uploader-cli#123]
**Describe the bug**
I am setting up a new account, but got stuck on OAuth.

**To Reproduce**
1. I use `gphotos-uploader-cli init` to generate config file.
2. Then I change the  account to my gmail account in config file.
3. Run `gphotos-uploader-cli`, it take me to google OAuth page, but the page throw an error:

```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:38373, does not match the ones authorized for the OAuth client.
```

**Expected behavior**
I should have OAuth done successfully.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Debian 
 - Version: bullseye

**Client (please complete the following information):**
gphotos-uploader-cli v0.8.0 (build: 39621fc)

**Additional context**
Is it any way to do OAuth manually? I can do OAuth manually.

**Comment by pacoorozco** [comment]
Hi @greensea 

I think that steps 1-3 are not enough to configure `gphotos-uploader-cli`. Google Photos OAuth is a bit tricky and it need few manual steps. 

1. [Obtain Google Photos API credentials](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#APIAppCredentials).
1. [Run the `gphotos-uploader-cli` for the first time](https://github.com/gphotosuploader/gphotos-uploader-cli#first-time-run).

Please, give us feedback if the documentation is detailed enough.

**Comment by phoenix1887** [comment]
@pacoorozco steps are good, got me through it. I just ran into the same problem as @greensea because they weren't listed initially. Good job with this btw 👍

**Comment by greensea** [comment]
Thank you, it works fine, now I am OAuthed.
I miss the Configure section in README.md. I think there could be some hits tell people to configure first while user run gphotos-uploader-cli the fisrt time.
