### ISSUE TITLE
Add command to reauthenticate accounts

### ISSUE THREAD

**Issue by plieningerweb** [gphotosuploader/gphotos-uploader-cli#125]
**Describe the bug**
Cannot refresh oauth token 

**To Reproduce**
1. was running before
2. updated form 0.5 release to 0.8 release
3. See error

**Desktop (please complete the following information):**
 - OS: Linux

```
./gphotos-uploader-cli 
2019/09/12 14:43:01 Token has been expired, refreshing
2019/09/12 14:43:01 could not refresh the token: oauth2: token expired and refresh token is not set
```

**Comment by plieningerweb** [comment]
thx, deleting key in gnome keyring worked. I think the command would make sense to add :)

**Comment by pacoorozco** [comment]
I will maintain it open to complete the command to reauthenticate

**Comment by Nelsyv** [comment]
I'm having the same `could not refresh the token: oauth2: token expired and refresh token is not set` on latest stable (v0.8.7). Is there a simple way to configure to get refresh tokens working properly? Or is it a bug in the code?

**Comment by tjwieg** [comment]
I'm having the same `could not refresh the token: oauth2: token expired and refresh token is not set` on latest stable (v0.8.7). It works for about an hour after first oauth, and then it's borked until I delete the keyring from `.local` and redo the first-time oauth.

Is this a known error, as an outstanding a bug in the code? (if so, is there a way to configure to get refresh tokens working properly?) Or does it sound like a problem on my system only?

I'm on Kubuntu LTS, if that's helpful.
