### ISSUE TITLE
0.8.2 keep printing the same thing over and over

### ISSUE THREAD

**Issue by antonmos** [gphotosuploader/gphotos-uploader-cli#129]
**Describe the bug**
``` Upload completed.[100%] Sent 4044948 of 4044948 bytes. Upload completed.[100%] Sent 4044948 of 4044948 bytes. Upload completed.[100%] Sent 4044948 of 4044948 bytes. Upload completed.[100%] Sent 4044948 of 4044948 bytes. Upload completed.[100%] Sent 4044948 of 4044948 bytes. Upload completed.[100%] Sent 4044948 of 4044948 bytes. Upload completed.[100%] Sent 4044948 of 4044948 bytes. ```

**To Reproduce**
1. Run it
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu

**Client (please complete the following information):**
 - Version 0.8.2

**Additional context**

**Comment by pacoorozco** [comment]
Uhm... let me check upstream... It worked well in my test environment :-( Sorry!

**Comment by pacoorozco** [comment]
I've found the problem... it was my fault :sweat_smile: 

I've modified the code upstream but I'm facing with a problem with int128/oauth2cli#3

I'm waiting to fix it!

**Comment by pacoorozco** [comment]
It should be fixed on latest release: [v0.8.3](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v0.8.3).

**Comment by jeffhoelter** [comment]
It works again - thank you!! 👍
