### ISSUE TITLE
Option "High Quality Upload"

### ISSUE THREAD

**Issue by phoenix1887** [gphotosuploader/gphotos-uploader-cli#133]
Option on a per directory basis "high quality uploads" -- will resize photos and videos before upload to allow user to upload with out Google storage limits

Photos are compressed to save space. If a photo is larger than 16MP, it will be resized to 16MP.

Videos higher than 1080p will be resized to high-definition 1080p.

**Comment by pacoorozco** [comment]
@phoenix1887 I've been thinking a lot about this in the past. Resizing pictures and videos is not easy. There are several ways to do it and It needs specific knowledge in the topic, so adding this feature to the CLI it could make it very complex to develop and maintain.

By the way, you can find very good projects dealing with batch resizing, like [this one](https://github.com/jarun/imgp) or [this other one](https://github.com/nfnt/resize).

I have to admit that the challenge is nice and interesting, but currently I don't think it would be supported bu `gphotos-uploader-cli`... 

Thanks for the feature request.
