### ISSUE TITLE
Please add an ability to specify files to upload in command line

### ISSUE THREAD

**Issue by X3KT0** [gphotosuploader/gphotos-uploader-cli#140]
I use a script to back up photos. I pass particular files to back up to that script, i.e. `script file.jpg /path/to/anotherfile.jpg /anotherpath/thirdfile.jpg`. In a moment of launching the script I always know where are the files to back up.

Could you please add a feature which would allow `gphotos-uploader-cli` to upload only explicitly given files, not a content of directory configured in config file? For example: `gphotos-uploader-cli file.jpg /path/to/anotherfile.jpg /anotherpath/thirdfile.jpg`or `gphotos-uploader-cli --only-upload file.jpg /path/to/anotherfile.jpg /anotherpath/thirdfile.jpg` or `gphotos-uploader-cli --only-upload file.jpg --only-upload /path/to/anotherfile.jpg --only-upload /anotherpath/thirdfile.jpg` ?

Thank you in advance.

**Comment by pacoorozco** [comment]
This feature sound good, but `gphotos-uploader-cli` is not very good at passing arguments. 
I mean, the original code I found was using a config file and the approach of having a config object (`Job`) to define the behaviour. 
It's not focus on individual files... It's a big change on the cli purpose :cry:  
You can use the same behaviour storing temporarily the files in a folder. `gphotos-uploader-cli` will upload it and remove the content afterwards.
