### ISSUE TITLE
Feedback: Upload now working without breaking all the time

### ISSUE THREAD

**Issue by plieningerweb** [gphotosuploader/gphotos-uploader-cli#145]
Just wanted to congratulate you guys, awesome job! :trophy: :+1: 

Since using 0.8.7 today, I have no interrupts and no required restarts anymore to upload several thousand images. I did only one run today and all images are successfully uploaded, nice!

Till the last version I used, 0.8.3 on linux 64, I still got an error every about 10 minutes and had to restart the program using cron. 

Very nice job, just wanted to give you that feedback!

(did not find better way than creation an issue, so maybe just close this)

**Comment by pacoorozco** [comment]
Thank @plieningerweb. You make my day awesome

![Awesome](https://media.giphy.com/media/rdma0nDFZMR32/source.gif)
