### ISSUE TITLE
Token expired and refresh token is not set

### ISSUE THREAD

**Issue by Eerovil** [gphotosuploader/gphotos-uploader-cli#147]
My environment (termux) has no keyring package available, so I'm stuck with file based token storage. As far as I know, the new refresh token feature requires using a keychain. Is this correct?

**Comment by Eerovil** [comment]
I've tried now using backends 'file' and 'pass'. Both work, but the refreshing part gives me trouble.

The logs: ```Token has been expired, refreshing
could not refresh the token: oauth2: token expired and refresh token is not set```

It seems that the user rfgamaral had the same issue, and fixed it: https://github.com/rfgamaral/docker-gphotos-uploader/issues/8#issuecomment-531930090

**Comment by pacoorozco** [comment]
Hi @Eerovil 

You are probably using a configuration folder created by a previous `gphotos-uploader-cli` version. Prior to v0.6.0 the token manager was not storing the refresh key, see #125 

If the problem persist, please copy all the output to be able to gather more information.

**Comment by Eerovil** [comment]
Deleting `.config/gphotos-uploader-cli/my.email@gmail.com` Does allow me to login again, but the issue persists: After some time I get the previous error.

**Comment by pacoorozco** [comment]
Can you copy & paste all the output, please? And the version, os and secrets backend.

**Comment by Eerovil** [comment]
`$ ./gphotos-uploader-cli push --debug
[info]   Token has been expired, refreshing
[fatal]  could not refresh the token: oauth2: token expired and refresh token is not set
`

Version info:

`git log -1
commit 62bf509081de95c50cec86abc7824b1336cf489f (HEAD, tag: v1.0.0-alpha1, origin/master)
Merge: 27bd2a4 b2358f3
Author: Paco Orozco <paco@pacoorozco.info>
Date:   Sun Nov 10 17:21:16 2019 +0100

    Merge pull request #155 from gphotosuploader/move-config-dir

    Move config dir to ~/.gphotos-uploader-cli
$`

OS is termux on LineageOS 16 (Android)

Secrets backend is "file"

**Comment by Eerovil** [comment]
Alright, the issue is resolved for my part.

When creating Oauth2 credentials in google apps console, I had used the type "Web Application". These types require passing `access_type=offline` in order to get a refresh token. Using an application with the type "Other" fixes the problem.

I propose a check for empty refresh token in the oauth module. Point the user to check for their oauth application type when it's empty.

**Comment by pacoorozco** [comment]
That has been covered in the README about how to set your credentials
