### ISSUE TITLE
uploaded photos are eating up storage

### ISSUE THREAD

**Issue by dirkvdplas** [gphotosuploader/gphotos-uploader-cli#148]
**Describe the bug**
In my google account I have set 'High quality', so in theory I should have unlimited space in Google Photos. However I noticed that photos uploaded with gphotos-uploader-cli are eating up storage

**To Reproduce**
2. Do tath on '....'
3. See error

**Expected behavior**
I would expect photos uploaded to Google Photos would not eat up storage because I have set 'High Quality' on my google account

**Screenshots**

**Desktop & Client versions (please complete the following information):**
 - Ubuntu 16.04
- gphotos-uploader-cli_0.8.7

**Additional context**
I run gphotes-uploaded-cli on a headless server. After starting the proces:
- I log in with browser via ssh-tunnel from my windows PC, and authenticate to windows
-this redirects my to localhost, which does fail on my Windows PC (so I copy paste the url to my headless server into wget which starts the upload process

**Comment by pacoorozco** [comment]
Hi @dirkvdplas 

It's the expected behaviour, see [Google Photos documentation](https://developers.google.com/photos/library/guides/api-limits-quotas#photo-storage-quality)

**Comment by mcevskb** [comment]
Hi, in that case there should be a warning info on the README

**Comment by pacoorozco** [comment]
PR is always welcomed :-D
