### ISSUE TITLE
Enable makeAlbums to use more than the last component of the folder name

### ISSUE THREAD

**Issue by morangorin** [gphotosuploader/gphotos-uploader-cli#150]
When a lot of photos are being shared, the last component of a file path can collide (e.g. 2018/Christmas with 2019/Christmas). 

GooglePhoto does not support hierarchical structures. Concatenating path elements would probably work for many use case (e.g. 2018_Christmas and 2019_Christmas or 2018/Christmas and 2019/Christmas).

**Comment by pacoorozco** [comment]
I've added a new configuration option to be able to set Album names based on the full path of the containing folder. See [documentation](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#makealbums).

**NOTE**: This is working with a 1.0.0-alpha version, which includes a **non-backwards** compatibility change. You must specify `push` command to upload your objects:

```
# before
$ gphotos-uploader-cli

# now
$ gphotos-uploader-cli push
```

**Comment by rysi3k** [comment]
@pacoorozco great! Could I ask for option to define separator between folders?
Or maybe some regex to remove some parts of generated album name? I have path 2019/2019 07 05-09 holidays/hotel/file.jpg and after this change I will have double 2019 at beginging. Thanks!

**Comment by pacoorozco** [comment]
I'm afraid that putting too much logic inside `gphotos-uploader-cli` it will be an over-killing solution. Using transformations is not easy through a CLI.

**Comment by rysi3k** [comment]
And what about replacing separator _ to something configurable? I would like to use | :)
