### ISSUE TITLE
Uploading videos fail (MKV not supported?)

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [gphotosuploader/gphotos-uploader-cli#151]
**Describe the bug**
Videos fail after upload, during "Sending media item creation" step, and are not added to Google Photos.

**To Reproduce**
1. Add file [test.mkv](https://github.com/gphotosuploader/gphotos-uploader-cli/files/3822067/test.mkv.gz) in the configured folder.
2. Launch gphotos-uploader-cli.
3. Video uploads until "Upload completed"
4. "Error while trying to create this media item"

**Expected behavior**
Video uploads fine.

**Screenshots**
```
$ ~/Apps/gphotos-uploader-cli/gphotos-uploader-cli 
Enter passphrase to unlock /home/dani/.config/gphotos-uploader-cli: 
2019/11/07 23:39:37 Token expiration: 2019-11-08 00:12:30.977902831 +0100 CET
2019/11/07 23:39:42 Uploading object: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
[DEBUG] Initiating upload and media item creation: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
gphotos-uploader: [DEBUG] Initiating file upload: type=resumable, file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
gphotos-uploader: [DEBUG] Initiating new upload session: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
gphotos-uploader: [DEBUG] Initiating upload session: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
gphotos-uploader: [0%] Sent 16384 of 3262633 bytes: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
...
gphotos-uploader: [100%] Sent 3262633 of 3262633 bytes: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
gphotos-uploader: Upload completed: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
[DEBUG] File has been uploaded: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv
[DEBUG] Sending media item creation: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv, retry=0
[ERR] Failed to create media item: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv, err=Failed: There was an error while trying to create this media item.
2019/11/07 23:40:17 [ERR] Failed to process media item: file=/home/dani/tmp/import-export/gphotos-uploader-source/test.mkv, err=Error while trying to create this media item, err=Failed: There was an error while trying to create this media item.
2019/11/07 23:40:17 all uploads done
2019/11/07 23:40:17 all deletions done
```

**Desktop & Client versions (please complete the following information):**
```
$ uname -a
Linux setna 4.15.0-66-lowlatency #75-Ubuntu SMP PREEMPT Tue Oct 1 06:11:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ ~/Apps/gphotos-uploader-cli/gphotos-uploader-cli version
gphotos-uploader-cli v0.8.7
```

**Additional context**
Same file (MKV) uploads just fine when drag-dropped to the Google Photo official UI.
Same issue with various file sizes, album names.
Issue does not happen when uploading same video transformed into an MP4 container (by doing `avconv -i test.mkv -codec copy test.mp4`).

**Comment by pacoorozco** [comment]
For some strange reason, the API is giving an error when you try to upload a MKV video. I've been debugging and it seems that it's Google who is giving it. I'm going to ensure if the Google Photos API is working with mkv files.

**Comment by pacoorozco** [comment]
Hi @daniel-callejas-sevilla 

I've been testing uploads of MKV files and it's working well. I've been using these MKV files (http://jell.yfish.us/). **Can you try it and give me more details?**

Remember run the `gphotos-uploader-cli` with `--debug` in order to have a more verbose output.

Thanks
