### ISSUE TITLE
Uploading not included video files 

### ISSUE THREAD

**Issue by rysi3k** [gphotosuploader/gphotos-uploader-cli#156]
**Describe the bug**
When configured includePatterns it looks like it only applies to image files, video file are uploaded even they are not in includePatterns.

**To Reproduce**
Config:
```
jobs: [
    {
      sourceFolder: /mnt/storage/photos
      makeAlbums: {
        enabled: true
        use: folderPath
      }
      uploadVideos: true
      includePatterns: [ "photos/20*" ]
      excludePatterns: [ ]
    }
  ]
```

Log during upload:
```
[info]   Not allowed by config: /mnt/storage/photos/dodrukować/2016/2016-10-01 10.01.59.jpg: skipping file...
[info]   Not allowed by config: /mnt/storage/photos/dodrukować/2016/2016-10-01 10.04.59.jpg: skipping file...
[info]   Not allowed by config: /mnt/storage/photos/dodrukować/2016/2016-10-02 15.07.29.jpg: skipping file...
[info]   Adding item to upload: /mnt/storage/photos/dodrukować/2016/2016-10-02 20.41.43.mp4
[info]   Not allowed by config: /mnt/storage/photos/dodrukować/2016/2016-10-07 13.37.27.jpg: skipping file...
[info]   Not allowed by config: /mnt/storage/photos/dodrukować/2016/DSCN2037.JPG: skipping file...
```

jpg file are skipped, mp4 is added to upload.

**Expected behavior**
Only files provided on includePattern list should be uploaded. In my example mp4 file should be skipped.

**Desktop & Client versions (please complete the following information):**
 - Operating System: macOS
 - Version 1.0.0-alpha

**Additional context**

**Comment by pacoorozco** [comment]
Hi @rysi3k , when you add `uploadVideos: true` you are configuring an `includePatterns` that allow all video files (see documentation).

So remove `uploadVideos` or add and `exclude Patterns` accordingly
