### ISSUE TITLE
EXIF test is not preserved

### ISSUE THREAD

**Issue by rg-software** [gphotosuploader/gphotos-uploader-cli#16]
When I upload a photo to Google Photos with drag-and-drop, the EXIF text becomes a caption of the photo. When I do the same with  the uploader tool, it shows file path instead of the caption.

**Comment by rg-software** [comment]
Thank you! I think that by default you supply empty (or nearly empty) metadata, though it should be possible to extract something sensible from images and include it into the upload query. Probably, "description" item [here](https://developers.google.com/photos/library/reference/rest/v1/mediaItems#MediaMetadata) should do the trick. I think any sensible approach (say taking this description from EXIF/ IPTC / XMP header) is better than nothing.

**Comment by pacoorozco** [comment]
Hi,
I've been testing this issue and i've not found any problem with EXIF information. All EXIF information is uploaded using the `gphotos-uploader-cli`. By default, `description` is extracted from file full path.
