### ISSUE TITLE
Uploading files multiple times while ignoring others

### ISSUE THREAD

**Issue by DrVanScott** [gphotosuploader/gphotos-uploader-cli#160]
I am using a self compiled version of commit 94ea306345d05c9232eaf3799c4e00b6fc875f03

Suppose uploading a folder with three image files:

    /home/user/Daten/Bilder/2016_11_test/IMG_4728.JPG
    /home/user/Daten/Bilder/2016_11_test/IMG_4729.JPG
    /home/user/Daten/Bilder/2016_11_test/IMG_4749.JPG

Starting the tool produces the following output

    [debug]  Token expiration: 2019-11-14 00:02:19.878983945 +0100 CET
    [info]   Adding item to upload: /home/user/Daten/Bilder/2016_11_test/IMG_4728.JPG
    [info]   Adding item to upload: /home/user/Daten/Bilder/2016_11_test/IMG_4729.JPG
    [info]   Adding item to upload: /home/user/Daten/Bilder/2016_11_test/IMG_4749.JPG
    [info]   3 files pending to be uploaded in folder '/home/user/Daten/Bilder/2016_11_test'.
    [debug]  Uploading object: file=/home/user/Daten/Bilder/2016_11_test/IMG_4729.JPG
    [debug]  Uploading object: file=/home/user/Daten/Bilder/2016_11_test/IMG_4729.JPG
    [debug]  Uploading object: file=/home/user/Daten/Bilder/2016_11_test/IMG_4749.JPG
    [done] √ all uploads done
    [done] √ all deletions done

Read the output carefully: While all three image files are added to the upload, only two of them are really uploaded (4729, 4749). file 4728 is missing, but 4729 has been uploaded twice.

Maybe a concurrency problem?

**Comment by pacoorozco** [comment]
I've refactored how concurrency is done. The bug is fixed, but I have some concerns about how I've implemented the JobQueue.

1) I can not make the code wait until all workers has finished. That's could have some undesirable problems, like publishing how many files has been uploaded.
2) I can not deal with error in `EnqueueJob.Process()`. So I'm not able to act accordignly.

Help is needed... **Can anyone do a code review (#161)?**

**Comment by DrVanScott** [comment]
Sorry, i don't have any experience with Go, so i cannot really help here. But is concurrency here really required? I think you would need quite a huge upload bandwidth to really gain, no?

**Comment by pacoorozco** [comment]
When you're uploading you're not using all your bandwidth. Working in parallel you take more profit from your internet connection:

```
$ time ./gphotos-uploader-cli --config ~/Downloads/gphotos-uploader-config push --workers 1 
[info]   9 files pending to be uploaded in folder '/home/xxx/Downloads/Sample-Pictures/Numeric'.
./gphotos-uploader-cli --config  push --workers 1  0,16s user 0,02s system 0% cpu 23,095 total
 
$ time ./gphotos-uploader-cli --config ~/Downloads/gphotos-uploader-config push --workers 5
[info]   9 files pending to be uploaded in folder '/home/paco/Downloads/Sample-Pictures/Numeric'.
./gphotos-uploader-cli --config  push --workers 5  0,16s user 0,03s system 2% cpu 9,087 total
```

23 second vs 9 seconds with only 9 files...
