### ISSUE TITLE
Uploads fail with "Unsupported protocol scheme" error

### ISSUE THREAD

**Issue by piether** [gphotosuploader/gphotos-uploader-cli#162]
**Describe the bug**
So I just installed tlhe uploader. Thanks for the effort! :clap:  But unfortunately the uploads fail with the following error:

`[error]  Failed to process media item: file=/home/pieter/Pictures/backup/2010/2010-11-04/IMG_1052.JPG, err=failed getting uploadToken for /home/pieter/Pictures/backup/2010/2010-11-04/IMG_1052.JPG: err=Post : unsupported protocol scheme ""`

I probably did something wrong in the setup, but the error message is not very helpful.

**To Reproduce**
What I did
1. I obtained a client id / secret by following these instructions https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#apiappcredentials
2. Ran `gphotos-uploader-cli init`
2. Put the credentials in the config file, modified the job to upload 1 folder as a test
3. Ran `gphotos-uploader-cli push`
4. Logged in with the right user
5. Got a warning that the app I created was not verified by Google, continued anyway
6. Gave permission to Photos API
7. Gave permission to manage my photos
8. Got a pop up from Ubuntu to create new keyring 
9. Got the error above for all images in the folder I put in the job 

**Expected behavior**
Expected it to upload the pictures :)

**Desktop & Client versions (please complete the following information):**
 - Operating System: Ubuntu 18.04.3 TLS
 - Version: gphotos-uploader-cli v1.0.0-alpha2% (yes the 2% was part of the output of the `version` subcommand)     

**Additional context**
I installed it using brew

**Comment by pacoorozco** [comment]
I've never seen this error before... can you paste your configuration file (remove credentials) and the full `--debug` output?

**Comment by piether** [comment]
I ran it with `--debug` but didn't become any wiser. So I ran it with `mitmproxy` capturing all requests.
All responses to the POST requests to https://photoslibrary.googleapis.com/v1/uploads are

`{
  "code": 16,
  "message": "The client has not activated the API."
}
`

So I went back to https://console.cloud.google.com/apis/library/photoslibrary.googleapis.com and enabled the API. And now it works
