### ISSUE TITLE
How to change localhost to IP

### ISSUE THREAD

**Issue by krycha88** [gphotosuploader/gphotos-uploader-cli#163]
I get a warning:
[info]   Opening browser to complete authorization.
[warn]   Browser was not detected. Complete the authorization browsing to: http://localhost:35517

I'm replacing http://localhost:35517/ with http://192.168.1.115:35517/
unfortunately it doesn't work, an attempt to connect to another PC ends with an error :( In previous versions it worked...

**Comment by pacoorozco** [comment]
Hi @krycha88 

You should browse to the provided URL (It's always localhost). We are not supporting headless setup, for this you can try [rfgamaral fork](https://github.com/rfgamaral/docker-gphotos-uploader).

Headless support will be supported in the future...
