### ISSUE TITLE
Feedback: I'm getting COde 400 Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by dtoader** [gphotosuploader/gphotos-uploader-cli#165]
I'm getting COde 400 Error: redirect_uri_mismatch

**Comment by dtoader** [comment]
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:52299, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/20637643488-1hvg8ev08r4tc16ca7j9oj3686lcf0el.apps.go

**Comment by pacoorozco** [comment]
Hi @dtoader 

I think you have not set the API Credentials properly. Please, [follow this documentation](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#APIAppCredentials), you should not set up any "URI response"

Let me know if worked
