### ISSUE TITLE
Tiomeout while exchanging authorization code and token

### ISSUE THREAD

**Issue by johnuopini** [gphotosuploader/gphotos-uploader-cli#166]
I can authenticate just fine, browser shows "SUCCESS in green" but then app fails with message below:

**Describe the bug**
[warn]   Browser was not detected. Complete the authorization browsing to: http://localhost:37275
channel 16: open failed: connect failed: Connection refused
[error]  error while authorization: error while exchanging authorization code and token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout
[fatal]  could not get a token: error while exchanging authorization code and token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout

**To Reproduce**
Connect to a remote system and bring connectivity locally using SSH Socks server (-D 127.0.0.1:5000), then use browser on localhost to authorize, authorization suceeds but then TLS on the client fails

**Expected behavior**
Oauth should succeed

**Desktop & Client versions (please complete the following information):**
- ARMv6 on Raspbian (rasp zero) cross compiled outside

**Comment by pacoorozco** [comment]
Hi Francesco

This CLI is not intended to be used in headless setups. There has been a
lot of discussions about if it could work or not in these kind of
situations, at the end I'm not putting too much focus on it.

@rfgamaral has done a huge effort using dockers:
https://github.com/rfgamaral/docker-gphotos-uploader please take a look to
it

Sorry for the inconvenience.

Paco

**Comment by johnuopini** [comment]
Thanks for the quick response, system is not headless actually, if i use a browser using a SOCKS server is creating a socket locally on the machine so its just like using it from the machine itself, i dont think this is realted to that. Anyway if its not something you can debug fair enough.

P.S. common approach in a lot of tools i have seen including GCloud client itself is to provide a link to get a token instead of using a local server, then once authorized you can paste your oauth response back to the local client

**Comment by pacoorozco** [comment]
Hi @johnuopini 

>  system is not headless actually

I have my doubts, but let's go and try to know why is not working. 

     +-------------------+          +----------+
     | +--------+        |SSH socks |          |
     | |chrome  |   +---------------+raspberry |
     | +--------+   |    |          |          |
     |     |        |    |          +----------+
     |     v        v    |
     |  localhost:port   |
     |                   |
     +-------------------+

The `gphotos-uploader-cli` open a web server in localhost address. This webserver is the one than the browser must connect to. Once in connected, an exchange is done between `gphotos-uploader-cli` and the Google Service (as described [here](https://tools.ietf.org/html/rfc6749#section-4.1))

So, I guess (and correct me if I'm wrong, `gphotos-uploader-cli` is running on the raspberry, it will create a webserver on that device, using localhost address and local port (37275 in your case), then you have created the SSH socket that redirects one port from your PC to the raspberry (port 5000) in that case, but the process running on the raspberry never gets the auth token. 

Please, take a look to the work from @rfgamaral, he has done exactly what you are trying to achieve: https://github.com/rfgamaral/docker-gphotos-uploader.
