### ISSUE TITLE
Wrong tag inserted from init "makeAlbums: use: folderNames" (should be folderName)

### ISSUE THREAD

**Issue by martyvis** [gphotosuploader/gphotos-uploader-cli#170]
**Describe the bug**
I noticed that while photos/videos were getting uploaded, they weren't getting tagged into an Album

**To Reproduce**
1. run ~/gphotos-uploader-cli/gphotos-uploader-cli init 
2. Edit as needed for account etc
3. run ~/gphotos-uploader-cli/gphotos-uploader-cli push
4. Photos are in Google Photos but not in an album 

**Expected behavior**

I was expecting the photos to be in an album

**Screenshots**

**Desktop & Client versions (please complete the following information):**
 - Linux (Ubuntu 19.04)
 - Version gphotos-uploader-cli v1.0.2

**Additional context**

It looks like the init sets the use tag (as below) to folderNames whereas documentation says it should be folderName (no s). I made the change and now my photo ends up in an album using the final folder name

makeAlbums: {
        enabled: true
        use: folderNames
      }

**Comment by pacoorozco** [comment]
Thanks @martyvis
