### ISSUE TITLE
Upload compressed pictures

### ISSUE THREAD

**Issue by wwikke** [gphotosuploader/gphotos-uploader-cli#174]
**Is your feature request related to a problem? Please describe.**
Drive/Photos gets full and reaches quotum.

**Describe the solution you'd like**
Upload compressed pictures in order to use the free tier.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
I don't see it listed in the configuration settings. Or is a google setting that is independent from the application?

**Comment by chrisadas** [comment]
I want this too, but looking at the Google API it does not seem to be possible right now.

https://developers.google.com/photos/library/reference/rest

**Comment by pacoorozco** [comment]
We can resize / recompress images before uploading it, but this will reduce the image quality for sure. The idea of this CLI is to upload images in the format you have in your folder. 

So, resizing should be covered by another tool, like [this one](https://github.com/jarun/imgp)
