### ISSUE TITLE
Problem with authorization

### ISSUE THREAD

**Issue by HydrelioxGitHub** [gphotosuploader/gphotos-uploader-cli#177]
**Describe the bug**
I've a problem with authenticating in docker. I've the message in my browser ( "You are authenticated, you can now return to the program. This will auto-close" ). But in the shell, I have the message : "

``` 
root@nas:~#` docker exec -it gphoto run                                                                                                                                                                             
[info]   Opening browser to complete authorization.

[warn]   Browser was not detected. Complete the authorization browsing to: http://localhost:29070

[error]  error while authorization: error while exchanging authorization code and token: Post 
https://oauth2.googleapis.com/token: x509: certificate signed by unknown authority

[fatal]  could not get a token: error while exchanging authorization code and token: Post https://oauth2.googleapis.com/token: x509: certificate signed by unknown authority
```

**Desktop & Client versions (please complete the following information):**
 - Docker

**Additional context**

**Comment by pacoorozco** [comment]
Hi @HydrelioxGitHub 
We're not providing any docker image, can you share with us the `Dockerfile` you're using? 
I guess the problem is on the docker system side, It's lacking some CA certificated.

**Comment by HydrelioxGitHub** [comment]
It's in this repo : https://github.com/rfgamaral/docker-gphotos-uploader
I've contacted the owner via Twitter and he ask me to open an issue on his repo.

**Comment by pacoorozco** [comment]
Yes probably is the proper one :-D
