### ISSUE TITLE
How can I enable "High quality (free unlimited storage)" option for uploads?

### ISSUE THREAD

**Issue by nobo73** [gphotosuploader/gphotos-uploader-cli#178]
Hi, first of all, thank you very much for providing this code.
I have tried to use this with docker on my NAS, and it works very well. It is really great!

However, all the uploaded are saved as "Original" (Full resolution that counts against your quota), and I want to change this to "High quality (free unlimited storage)" / Great visual quality at reduced file size.
I can push the button to change "Original" to "High quality", every time the storage becomes full, but if it is possible, I want to have an option to upload and saved photos as High quality (free unlimited storage)".
Thanks,

**Comment by ketz** [comment]
+1

**Comment by pacoorozco** [comment]
There is no way from the Google Photos API to call this 'button'. See [here](https://developers.google.com/photos/library/guides/api-limits-quotas). So the alternative is that you resize / reformat images prior uploading it to Google Photos. 

`gphotos-uploader-cli` is not intended to do it.

**Comment by nobo73** [comment]
Thank, I understand the reason.

**Comment by eGit** [comment]
In my settings I have "High Quality" selected. So all uploads shouldn't count towards my quota. And truly, if I upload videos/images via my browser or Android app, it doesn't count towards my quota. I can upload all day!

Why is the upload via gphotos-uploader-cli always counting towards my quota. Why can the other upload solutions respect the settings of "High quality" ?

**Comment by pacoorozco** [comment]
Hi @eGit 

There is a previous comment on this issue explaining it. The comment is that [one](https://github.com/gphotosuploader/gphotos-uploader-cli/issues/178#issuecomment-578698003). Google Photos API **doesn't allow** to upload using High quality quota.

You can read it on Google documentation above.

**Comment by eGit** [comment]
Wow. Google is sneaky. Did they put this limitation in there to sell their cloud storage?

And the browser and Android Photos app use different APIs? Is that not unfair competition if they can use special APIs? Well, I guess Apple is doing the same, so no surprise.
