### ISSUE TITLE
How does "Track already uploaded files" work?

### ISSUE THREAD

**Issue by chrisadas** [gphotosuploader/gphotos-uploader-cli#179]
Does the program keep track of what it already uploaded using some logging?

Or does it compare image hashes with those on Google Photos for a match and exclude from upload?

I am asking mainly to try to understand whether, if I use the program to upload some time ago, and today run the program again on a fresh install, would the program knows which images were already uploaded last time? (using a different installation of the program)

**Comment by syco** [comment]
Short answer, it would re-upload the files,
as far as I can understand it keeps track of already uploaded files in "~/.gphotos-uploader-cli/uploads.db"

knowing the right database structure it might be possible to populate uploads.db with a bash command like "find files | xargs ldbadd ...." so to avoid duplicates.

**Comment by pacoorozco** [comment]
Hi @chrisadas 

@syco is totally right... `gphotos-uploader-cli` keeps track of the uploaded files using a local stored database.

**Comment by chrisadas** [comment]
Thank you both for your replies.

It could be a good addition to allow retrieving photo file names from gphotos library using mediaItems.list and upload only those that does not match. The matching will not be perfect like hash comparison, but I can see it still being useful.
