### ISSUE TITLE
Feedback: Headless Server

### ISSUE THREAD

**Issue by scott2020** [gphotosuploader/gphotos-uploader-cli#180]
Great program!  I got it working well, but it is difficult on a headless server.  On my server I did set it up and loaded a browser to do the Oauth, but it only seems to work on that session.  If I SSH with the same user and run it again, it wants to do the Oauth over again.  Any suggestions?

**Comment by pacoorozco** [comment]
Hi @scott2020 

That has been asked several times (I need to put a note somewhere :sweat_smile: ) Take a look to https://github.com/rfgamaral/docker-gphotos-uploader where @rfgamaral has done a brilliant job in this regards.
