### ISSUE TITLE
Geting "400: Bad Request" Error

### ISSUE THREAD

**Issue by steven-murray** [gphotosuploader/gphotos-uploader-cli#181]
**Describe the bug**
I'm pretty sure I set myself up on Google and copied in the Client ID and Secret to my config. 
However, the first time I ran `push` every file errored with something like:

```
[error]  Album creation failed: name=StevenPhone, error=googleapi: Error 403: Photos Library API has not been used in project 466066290713 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/photoslibrary.googleapis.com/overview?project=466066290713 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

So I visited that URL, and made *another* Client ID and Secret, put them in my config, but now it is giving me this error:

```
[info]   Token has been expired, refreshing
[fatal]  could not refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```
I'm not very handy with Oauth stuff, so I'm probably doing something wrong, sorry! 
Any suggestions?

**Desktop & Client versions (please complete the following information):**
 - Operating System: linux (Ubuntu)
 - Version 1.0.4

**Comment by pacoorozco** [comment]
Hi @steven-murray 

Sorry for the delay, I've been testing it and it's working well. Can you repeat the process of enablig Google Photos API to ensure that you didn't miss any step?

Thanks

**Comment by pacoorozco** [comment]
@steven-murray Can you add any update on that?

**Comment by steven-murray** [comment]
Sorry, I haven't had the time to get to it. I might be a couple of weeks --
I'll let you know as soon as I do!

**Comment by pacoorozco** [comment]
No more feedback!

**Comment by antonmos** [comment]
i just ran into the same problem. I set up a new project, but it didnt help.
I used it on this computer many months ago.
where is the refresh token stored? do i need to clear it?

**Comment by pacoorozco** [comment]
Hi guys!
I've tried to upload some pictures and it's working wo/ any problem. 
```
$ ./gphotos-uploader-cli --debug --config ~/.config/gphotos-uploader-cli push
[debug]  Worker #3 is starting
[debug]  Worker #5 is starting
[debug]  Worker #4 is starting
[debug]  Worker #1 is starting
[debug]  Worker #2 is starting
Enter passphrase to unlock /home/xxx/.config/gphotos-uploader-cli: 
[info]   Token has been expired, refreshing
[debug]  Token expiration: 2020-07-02 09:33:04.293179019 +0200 CEST m=+3603.838353011
[info]   Found item to upload: /home/xxx/Downloads/Test/Album_20200702/AeoniumLeaf_EN-AU7200082197_1920x1080.jpg
[info]   1 files pending to be uploaded in folder '/home/xxx/Downloads/Test'.
[debug]  Worker #3 processing: /home/xxx/Downloads/Test/Album_20200702/AeoniumLeaf_EN-AU7200082197_1920x1080.jpg
[debug]  Successfully processing /home/xxx/Downloads/Test/Album_20200702/AeoniumLeaf_EN-AU7200082197_1920x1080.jpg
[info]   1 processed files: 1 successfully, 0 with errors
[debug]  Worker #1 is stopping
[debug]  Worker #2 is stopping
[debug]  Worker #3 is stopping
[debug]  Worker #4 is stopping
[debug]  Worker #5 is stopping
[debug]  Shutting down File Tracker service...
[debug]  Shutting down Upload Tracker service...
[debug]  Shutting down Token Manager service...
[debug]  All services has been shut down successfully
$ ./gphotos-uploader-cli version
gphotos-uploader-cli v1.0.6-3-g4f32989%       
```
**Can you paste the same? Can you add the version?**

**Comment by antonmos** [comment]
```
$ ./gphotos-uploader-cli --debug push
[debug]  Worker #1 is starting
[debug]  Worker #2 is starting
[debug]  Worker #3 is starting
[debug]  Worker #4 is starting
[debug]  Worker #5 is starting
[info]   Token has been expired, refreshing
[debug]  Worker #1 is stopping
[debug]  Worker #2 is stopping
[debug]  Worker #3 is stopping
[debug]  Worker #4 is stopping
[debug]  Worker #5 is stopping
[debug]  Shutting down File Tracker service...
[debug]  Shutting down Upload Tracker service...
[debug]  Shutting down Token Manager service...
[debug]  All services has been shut down successfully
[fatal]  could not refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
$ ./gphotos-uploader-cli version
gphotos-uploader-cli v1.0.6
```

**Comment by antonmos** [comment]
there might be some relevant info here, but i am not sure how to troubleshoot further...it has been over 6 months since i used it last.
https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35#.eqa5iwbkt

Q1: is the refresh token saved somewhere on the filesytem?  does it need to be deleted or does `auth` start from scratch?Q2: do we need to add scope to the OAuth Consent Screen setup?
![image](https://user-images.githubusercontent.com/2713/86397201-fe762e00-bc68-11ea-987e-1699f68f1e22.png)

**Comment by pacoorozco** [comment]
Hi @antonmos 

It seems that you didn't grant all the required permissions. So i suggest you execute `gphotos-uploader-cli init` to setup Google Permission again.

**Comment by antonmos** [comment]
i just ran `./gphotos-uploader-cli init --force`, then copied over my config.hjsonthen ran 

```
$ ./gphotos-uploader-cli push
[info]   Token has been expired, refreshing
[fatal]  could not refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

**Comment by pacoorozco** [comment]
Hi @antonmos 

Sorry, I think I was missunderstood. I wanted that you renew all the credentials. To do so:

1. Go to https://console.developers.google.com/ and login with your user
2. Look for Google Photos API.
3. Go to credentials and remove all credentials. You can close your browser now.
4. Go to your terminal and run `gphotos-uploader-cli init --force`
5. Go to your config folder and delete your account credentials. There will be a file named as your Google account.
6. Edit configuration file and set your data
7. Run `gphotos-uploader-cli push`. Follow [this documentation](https://github.com/gphotosuploader/gphotos-uploader-cli#first-time-run). 

Tell me how the process was!

**Comment by antonmos** [comment]
> Go to your config folder and delete your account credentials. There will be a file named as your Google account.
I did not have this file. Maybe cause the last time it worked, i was using version v0.8.4?  

> Create credentials by clicking the Create credentials → OAuth client ID option, then pick Other as the application type and give it a name (example: gphotos-uploader-cli).
There is no "other" option:
![image](https://user-images.githubusercontent.com/2713/86518607-44adc780-bdf8-11ea-972f-efe6a1da4ad3.png)
so i selected "desktop"

after i ran `gphotos-uploader-cli`, i once again got 
```
./gphotos-uploader-cli push
[info]   Token has been expired, refreshing
[fatal]  could not refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

```

**Comment by antonmos** [comment]
Have you tried this process recently on your computer? i wonder if google changed something on their end

**Comment by pacoorozco** [comment]
The option you selected "Desktop app" seems to be correct. It seems Google has renamed it.

I have a different behaviour (I'm using linux). 
```
$ /gphotos-uploader-cli --debug push       
[debug]  Worker #2 is starting
[debug]  Worker #1 is starting
[debug]  Worker #4 is starting
[debug]  Worker #3 is starting
[debug]  Worker #5 is starting
[debug]  Token has not been retrieved from token store: failed retrieving token from keyring
[info]   Opening browser to complete authorization.
Opening in existing browser session.
[0706/090744.200687:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
[51168:51168:0706/090744.291926:ERROR:broker_posix.cc(43)] Invalid node channel message
[51164:51164:0100/000000.391390:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[51164:51164:0100/000000.392368:ERROR:broker_posix.cc(43)] Invalid node channel message
```

Something has been broken lately... I need to take a deeper look and then go for the "400"s

**Comment by pacoorozco** [comment]
I'm going to create a bug for the `NaCl helper` error #204

**Comment by pacoorozco** [comment]
Hi!

I've temporary fixed the problem changing the way OAuth token is retrieved. Since **v1.0.7** `gphotos-uploader-cli` will not open a browser in your system. Instead of it, a URL is shown, **please visit this web address using your preferred browser**, complete the Google authorisation flow **and paste the code** that Google will supply as a final step.

**Comment by pacoorozco** [comment]
Can you confirm that it's working for you? @steven-murray @antonmos

**Comment by maltokyo** [comment]
This is a really cool and needed change, thank you @pacoorozco !! Can use now on headless!

**Comment by antonmos** [comment]
Unfortunately, no change for me :(
still the same 400 error

**Comment by steven-murray** [comment]
This seemed to fix things for, thanks! To be clear, I am using this on Manjaro linux, I installed by manually running `make build` in the fully updated master branch of the repo. I also created a new OAuth credential following the docs. Everything pushed well!

**Comment by pacoorozco** [comment]
@antonmos can you give me more details, which version are you using? what is the process you are following?

**Comment by antonmos** [comment]
i am using v1.0.7 and followed your instructions from https://github.com/gphotosuploader/gphotos-uploader-cli/issues/181#issuecomment-653378871

**Comment by antonmos** [comment]
i set it up with a completely new Google Account and it worked. But, it is still not working with my original google account.

Could you answer my questions from above "is the refresh token saved somewhere on the file system?"  it seems like it is trying to refresh instead of starting from scratch.

**Comment by pacoorozco** [comment]
The credentials, including refresh token, are stored in the secrets manager. `gphotos-upload-cli` support several services, which can be configured through `SecretsBackendType` [1](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#secretsbackendtype).

You can remove your credentials and tryit again.

**Comment by antonmos** [comment]
That was it. On ubuntu, i did `sudo apt-get install seahorse` then ran `seahorse` and deleted 4 secrets that mentioned gphotosuploader.  Then, i tried `gphotos-upload-cli push` again and got the link.

Thanks!
