### ISSUE TITLE
installation via go get is broken

### ISSUE THREAD

**Issue by adojaan** [gphotosuploader/gphotos-uploader-cli#183]
**Describe the bug**
When installing via  go get github.com/gphotosuploader/gphotos-uploader-cli
error is displayed

package google.golang.org/api/gensupport: cannot find package "google.golang.org/api/gensupport" in any of:
	/usr/local/go/src/google.golang.org/api/gensupport (from $GOROOT)
	/home/kristjan/gphotos-uploader-cli/src/google.golang.org/api/gensupport (from $GOPATH)

**To Reproduce**
1. install latest go - in my case 1.14, verify it
go version
go version go1.14 linux/amd64
2. try to install go get github.com/gphotosuploader/gphotos-uploader-cli
error is displayed
package google.golang.org/api/gensupport: cannot find package "google.golang.org/api/gensupport" in any of:
	/usr/lib/go-1.10/src/google.golang.org/api/gensupport (from $GOROOT)
	/home/kristjan/gocode/src/google.golang.org/api/gensupport (from $GOPATH)

**Expected behavior**
install should go fluently

**Screenshots**

**Desktop & Client versions (please complete the following information):**
 - Operating System: linux (ubuntu 18.04) running on WSL2 on Windows 10

**Additional context**
Maybe golang problem. I could override the problem when manually downloading golang and symlinking gensupport folder from where it existed to where it was expected.

**Comment by pacoorozco** [comment]
The googleapis guys has changed the location of `gensupport` to make it internal, as they has been explaining [here](https://github.com/googleapis/google-api-go-client/issues/398).

This means that we need to update [googlemirror repository](https://github.com/gphotosuploader/googlemirror) to add `gensupport` as vendor :-(

I'm going to follow it in the upstream repository.
