### ISSUE TITLE
upload to free space only

### ISSUE THREAD

**Issue by frischnetz** [gphotosuploader/gphotos-uploader-cli#188]
**Is your feature request related to a problem? Please describe.**
The normal upload eats up the non-free google drive space.

**Describe the solution you'd like**
I'd like an option to choose between free, unlimited uploads and uploads that use up the limited google photos space.

**Describe alternatives you've considered**
Drag-and-drop into the browser works, but this is not automated like the script.

**Comment by pacoorozco** [comment]
Hi @frischnetz 

This has been requested several times, let me share with you the context:

**Photo storage and quality**
All media items uploaded to Google Photos using the API are stored in full resolution at original quality. They count toward the user’s storage, and **it's not possible** to change that. It's a limitation that imposes Google Photos using its API. 

You can recover your storage following [this how-to](https://support.google.com/photos/answer/6220791?co=GENIE.Platform%3DDesktop&hl=en).

The option to choose between different tiers is not in our hands. Google Photos API **can not** upload towards "High quality" tier.

Thank you very much for using the CLI and for the feedback.

**Comment by frischnetz** [comment]
Thanks for clarification!

**Comment by khurshid-alam** [comment]
@pacoorozco I just uploaded a pic with rclone and it does't count toward space. In photos settings I have high quality selected. How this cli changing that settings? There is no api for it ? Can you revisit this?
