### ISSUE TITLE
Assign thumbnail to video during upload..?

### ISSUE THREAD

**Issue by eGit** [gphotosuploader/gphotos-uploader-cli#191]
**Is your feature request related to a problem? Please describe.**
Google Photos in the browser or the mobile app doesn't properly label videos. You always have to click on the "info" button to see the filename of the video. Also the thumbnail of the video doesn't help, since Google uses the first frame of the video.

**Describe the solution you'd like**
I was hoping that it is possible to assign a thumbnail to the video. The thumbnail I would provide and it would contain for example the filename.

**Describe alternatives you've considered**
Maybe write your own UI client to browse your videos, which displays the filename below each video.

**Additional context**

**Comment by pacoorozco** [comment]
So the feature you are requesting is the ability of adding your own thumbnail image to be used by Google Photos as thumbnail... am i right?

**Comment by eGit** [comment]
Basically yes. Is this not covered by the Google Photos API?

**Comment by pacoorozco** [comment]
Unfortunately **It's not supported by [Google Photos Api](https://developers.google.com/photos/library/reference/rest/v1/mediaItems#Video)**

**Comment by eGit** [comment]
Maybe a workaround would be possible on your end? Videos can be edited without re-encoding if you split at i-Frames. ffmpeg can do this. You cannot do full edits (add filters, etc.) but you could add an image or short video at the beginning of a video.
This image/video could be defined by the user or automatically generated to show the filename of the video.
