### ISSUE TITLE
Have the first run on interfaces other than lo

### ISSUE THREAD

**Issue by hujuice** [gphotosuploader/gphotos-uploader-cli#193]
I'm frustrated because I was trying to install gpc in my VPS, but in the first run only the http://127.0.0.1:44961 address is available. Obviously, I have no browser there.
If I could use another interface, I could access from my browser.

I would like that the internal http server could respond on any interface.
Alternatively, it can be asked, before running.

Thanks,
HUjuice

**Comment by pacoorozco** [comment]
**This script is not intended to be run in a headless platform**. Take a look to the terrific job that @rfgamaral has done: https://github.com/rfgamaral/docker-gphotos-uploader
