### ISSUE TITLE
Resume after error or standby..?

### ISSUE THREAD

**Issue by eGit** [gphotosuploader/gphotos-uploader-cli#194]
**Is your feature request related to a problem? Please describe.**
I wrote a Youtube uploader a while ago and resume after upload error or standby was no problem. It recovered if the internet connection was disturbed or some other temporary problem was later resolved.
I played a little afterwards with the GPhotos API and it looked pretty much identical. I think resume was possible.

**Describe the solution you'd like**
For me gphotos-uploader-cli does not attempt to resume. Once a file failed, it failed completely. You need to restart the g-u-cli and upload it from the start.

P.S.: I can upload files although my account quota is used up. It doesn't fail immediately but uploads for hours and only then seem to notice that my account quota is used up. Can't such a check be done at the start of the upload. Fail early?

**Comment by pacoorozco** [comment]
Hi @eGit 

`gphotos-uploader-cli` is retrying HTTP calls based on response codes (https://github.com/gphotosuploader/google-photos-api-client-go/blob/master/lib-gphotos/internal/uploader/uploader.go). It's following the HTTP standards to work on it.

For example, In case that your request's quota has been raised, the uploader will use exponential backoff to retry and try to solve the issue. But in case of your storage quota has been reached, you should do an action to fix it, so It makes no sense to continue retrying. 

All uploads are resumable, so If you had a network problem uploading a file, the next time to try to uploade it will NOT start from the begining. It will continue from the point i failed.

So, my question is... what is the use case you would like to resume after error?

**Comment by eGit** [comment]
For example it logs an error for the files currently uploading when I go into standby and then wake it up several hours later. I think it will just finish the current 'push' but not try to resume those files. I have to restart gphotos-uploader-cli push for the files to finish uploading.
Shouldn't it realize that there were some errors and attempt a resume in the same push-session?

Maybe I am mistaken and misinterpreted the issue. In that case please feel free to close it.

**Comment by pacoorozco** [comment]
Hi,

When a file is marked as error is because `gphotos-uploader-cli` tried to resume the upload several times (3 times in fact). It retries for HTTP responses that are retryable (500, 429...) but, If the problem persist, it's probably because you need to do an action.

This avoids sending requests to Google that are not retryable and it could end on a ban from them.

I hope now it's clearer.

**Comment by eGit** [comment]
Ok thanks. I wonder why it then fails when waking up from standby? Is it trying to quickly 3 times before the Wifi has reconnected? Maybe make a 60 sec pause between retries?

I think you already mentioned enhanced info logging in upcoming releases. I think this would resolve most of my confusion on what is actually happening. Most people using CLI tools are a little more advanced users...so advanced logging info makes sense and will be read ;)

**Comment by pacoorozco** [comment]
Have you tried the `--debug` flag? It should give you a high level of verbosity in order to answer your questions. Reach me if it's not doing it.
