### ISSUE TITLE
Help with Error 409

### ISSUE THREAD

**Issue by 3thanfox** [gphotosuploader/gphotos-uploader-cli#196]
Hello, great program here, really appreciate you sharing it.  I was hoping someone could help clarify an error I'm receiving on quite a few jpg files when running the program.  For the most part, the program is running fine.  I have 40,000+ photo/video files it's slowly uploading day by day in-between hitting the max limit.  But the last few days have introduced a new error that I don't understand/can't find reference for a fix online:

[error]  error while trying to create this media item, err=unexpected error response: file=/filepath/filename.jpg, err=googleapi: Error 409: The operation was aborted., aborted
[fail] X Error processing /filepath/filename.jpg

 - Operating System: Ubuntu 18.04
 - gphotos-uploader-cli v1.0.6

Know what I can do to fix this?  Or is the error too generic to be much use for this issue?  I was hoping to pull more info from the log file, but the LOG I looked at in ~/.gphotos-uploader-cli/uploads.db/ didn't have the detail I was hoping for.  Is it possible to configure the client to generate more details?  Thanks!

**Comment by pacoorozco** [comment]
Hi @3thanfox 

This HTTP response code is `HTTP Conflict` code and it's produced by Google Photos API. I've been searching within the [documentation](https://developers.google.com/photos/library/guides/upload-media) and I haven't seen what it could produce it.

I propose you review some things:
- Try to upload the same image to the same album using Google Photos UI. Does it work?
- Try to review the number of objects that the target album has. There's a limitation of 2000 object per album.

**Comment by 3thanfox** [comment]
Thanks for the quick reply!  

- The same photos DO upload to google photos no problem using simple drag-drop in Firefox on photos.google.com.
- The number of objects in album is not the culprit in this case; the folders in question all have fewer than 500 photos (most have fewer than 100)

I guess I'll wait for gphotos-uploader to get through as many files as it can and then manually add the rest.  I'll post again if anything changes, or let you know how it all turns out when it gets through all 40k photos.

**Comment by 3thanfox** [comment]
I just wanted to close this out.  I never figured out what the 409 error was, but it was only happening to ~100 of the photos.  After the client completed uploading everything it could, I just manually dropped the rest into a browser, transferred no problem.
