### ISSUE TITLE
How to get started when photos already present in gphotos?

### ISSUE THREAD

**Issue by eng3** [gphotosuploader/gphotos-uploader-cli#199]
I am just starting.  I already have 99% of my library on google photos (back in the day with Picasa and through manual album creation).  I tried letting the upload go on its own (failing every file) thinking the upload database will eventually become up to date and any new albums should get created moving forward.  I stopped gphotos because I reached my upload limit.  Upon restarting, I now get "uploads.db, err=resource temporarily unavailable".  I guess the uploads.db got corrupted?  What is the recommended way to get around this issue and the general issue of already having a library on google photos.  I'd prefer not to completely delete all my uploaded albums since I'm not 100% sure this tool even works for me.

_Originally posted by @eng3 in https://github.com/gphotosuploader/gphotos-uploader-cli/issues/49#issuecomment-638876576_

**Comment by eng3** [comment]
Is there a way to recreate the database without re-uploading?  Otherwise, everytime the database becomes corrupted, I have to reupload which can take days.  (ofcourse, I can try to keep backups of the db). What do you recommend for someone like me getting started with your tool who already has 99% of their photo collection on google photos?  Do I just let it run for a few days to build the database?  Should I really delete me entire google photos and reupload?

**Comment by pacoorozco** [comment]
I think the CLI should provide a way to mark all files on the tree as already uploaded. This will make easier to start the process when you're sure that 99% of your files are already uploaded. 

What it would happen to the 1% is interesting... because there is not "easy" way to sync from Google Photos. So #182 is implementing what you are missing.

**Comment by cameronus** [comment]
@pacoorozco I have the same issue as eng3 here with about 800 GB already on Google Photos and a cache of new files I need to upload. Any update on whether the "marking" feature will be implemented in a future version? Is there another (better) way maybe to download a manifest from the API and compare it to the source folder to see what's already been uploaded?

@eng3 Did you end up figuring out a solution to your problem? Would appreciate any pointers!

**Comment by eng3** [comment]
No and with google stopping the unlimited storage, I've started uploading through my old pixel to get unlimited, thereby rendering this application useless to me

**Comment by pacoorozco** [comment]
Hi @cameronus 

There is not a command to mark files as already uploaded. **But, you can exclude its folders using `excludePatterns` configuration field**. It will do the same than marking files as already uploaded.

>  Is there another (better) way maybe to download a manifest from the API and compare it to the source folder to see what's already been uploaded?

AFAIK there is no way to obtain this from Google Photos. The unique way to do it is to upload the file to the Google Photos API and get the Media.Id from Google.

`gphotos-uploader-cli` try to reduce the number of calls to the API just caching which files were already uploaded by this script.

**Comment by kaskavalci** [comment]
It seems it's relatively easy to repair a corrupted leveldb database.

https://smithfarm-thebrain.blogspot.com/2016/11/how-to-repair-leveldb-database.html

This worked for me:

1. Install leveldb python module `pip install leveldb`
2. Find your config directory. mine is `/usr/local/gphotos-config/`
3. Execute the script 

```python
import leveldb
leveldb.RepairDB('/usr/local/gphotos-config/ongoing_uploads')
leveldb.RepairDB('/usr/local/gphotos-config/uploaded_files')
```
