### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by ghost** [gphotosuploader/gphotos-uploader-cli#20]
Does this preserve the photo taken dates or does the Google photos date become the uploaded date?

**Comment by nmrshll** [comment]
For now it loses metadata at upload, so the date becomes the upload date. 
It's a bug / needs work, it's intended to keep the metadata.

**Comment by kapone3047** [comment]
Is there any update or progress on retaining metadata? This is the one thing holding me back from using gphotos-uploader-cli at the moment. I have a new headless home server setup (was previously running Windows 10 headless), and backing up my photos to Google Photos is the one last missing piece

**Comment by driv** [comment]
I don't see this happening, was something fixed?

**Comment by ryanov** [comment]
I mostly see metadata being used as well. Uploaded thousands of photos from the mid 2000s successfully this week. I suspect the photos that uploaded with today's date had no metadata (I didn't check).

**Comment by pacoorozco** [comment]
All metadata is uploaded with the file.But Google Photos remove (ignore) part of these metadata
