### ISSUE TITLE
Albums not being created from folder names

### ISSUE THREAD

**Issue by byalextran** [gphotosuploader/gphotos-uploader-cli#203]
**Describe the bug**
The `makeAlbums` settings don't appear to be working properly with the following configuration: 

```

{
  SecretsBackendType: auto,
  APIAppCredentials: {
    ClientID:     "REDACTED",
    ClientSecret: "REDACTED",
  }
  jobs: [
    {
      account: REDACTED
      sourceFolder: /Volumes/backups/mac-mini/My Documents/My Pictures/2009/2009-12-17 - Ansley's Farewell Lunch/
      makeAlbums: {
        enabled: true
        use: folderName
      }
      deleteAfterUpload: false
      uploadVideos: true
      includePatterns: []
      excludePatterns: [ "*.db", "*.ini" ]
    }
  ]
}
```

**To Reproduce**
1. Use the above configuration. 
2. Run the `push` command. 
3. Wait for the images to finish uploading. 
4. Search Google Photos for one of the uploaded images. 
5. Look at the Info for that image and see which album it's saved in.

**Expected behavior**
I expect the images to be uploaded into a Google Photo album called `2009-12-17 - Ansley's Farewell Lunch`. Unfortunately, they're not uploaded into any album. 

**Screenshots**
You'd normally see the album listed in this screenshot. And I'm not sure if this is related, but the full image path is saved into the image description. That's unexpected behavior to me as I would assume the description would be left alone. 

<img width="360" alt="Screen Shot 2020-06-26 at 00 49 47 AM" src="https://user-images.githubusercontent.com/455406/85825201-3d772180-b747-11ea-8ebe-6de99983d4c5.png">

**Desktop & Client versions (please complete the following information):**
 - Operating System: Mac 10.14.6
 - Version: gphotos-uploader-cli v1.0.6

**Additional context**
I've tried wrapping the `sourceFolder` in double quotes and also including/excluding the trailing slash hoping that would fix things. Unfortunately, none of those things fixed the issue. 

If it matters, the folder exists on a NAS drive.

**Comment by pacoorozco** [comment]
Hi @byalextran 

This is the expected behaviour. All configuration is related to the `sourceFolder`, so album creation will be done for child folders inside `sourceFolder`.

I've modified the documentation to make it more present:
https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#makealbums
