### ISSUE TITLE
Question: Will it sync (skip upload of files that already exist on GPhotos with same name/size etc) on second run?

### ISSUE THREAD

**Issue by maltokyo** [gphotosuploader/gphotos-uploader-cli#207]
**Describe the bug**

Sorry not a bug, just a question, I was not sure where to ask and could not find in the docs

** Question **

Will this sync (skip upload of files that already exist on GPhotos with same name/size etc) on second run?

So, if I upload a dir with 1000 images, and then add two more tomorrow and run on the same folder, would it just upload the two new ones?  If so what criteria does it check for existing files with (size/name/checksum?)? 

Thank you very much, looks cool!

**Comment by pacoorozco** [comment]
Hi @maltokyo 

> Will this sync (skip upload of files that already exist on GPhotos with same name/size etc) on second run?

As it's mentioned on the documentation "Track already uploaded files: uploads only new files to save bandwidth". It keeps a local database (under config directory) and look for md5 + modification date.

So only the new two files will be uploaded.

**Comment by maltokyo** [comment]
Great. Thank you. Sorry to have missed that.
