### ISSUE TITLE
Feedback: This is great

### ISSUE THREAD

**Issue by grumpyjames** [gphotosuploader/gphotos-uploader-cli#214]
Here's how things went for me today:

1. Downloaded and built locally
2. Edited the config file
3. Configured auth (wow, this is complicated, thank you for the documentation)
4. Uploaded some photos (it just worked!)
5. Played around with includes/excludes (also just worked, and is a really good shape for, say, not trying to upload 10 years of photos in one go!)

Many thanks for putting this together!

**Two tiny suggestions:**
  
```
deleteAfterUpload: false
```
should perhaps be the default. I read the config file carefully and did some experiments with scratch directories before running this against my archive directory; imagine if someone else did not!

Secondly, it looks like the google photos web interface is quite slow to detect new albums created by the API. It might be worth adding something to the console output to reassure the user this has happened - I had long enough to start opening an issue, but then I looked back at the web interface, and the album had appeared.

Thanks again!

**Comment by grumpyjames** [comment]
Oh, a tiny third suggestion: perhaps have a `--dry-run` mode?

**Comment by pacoorozco** [comment]
Hi @grumpyjames 

Your feedback and suggestions are super welcomed! I'm going to change the default for `deleteAfterUpload`, I think your're totally right.

Let me ask you more details about your last comment. What the `--dry-run` mode would do?

**Comment by grumpyjames** [comment]
Re: `--dry-run`. 

Rather than actually calling the photos API, it would just tell you what it _would_ do.

This can be useful to test changes to the `includePatterns` and `excludePatterns`. 

An example:

I am slowly been working my way through my photo archive. My directories start with the year in which the photos were taken, so like this:

```
20200302-album-one
20200103-another-album
20191011-an-older-album
```

Using the tool for the first time, my config looked like this:

```
includePatterns: ["2020*"]
excludePatterns: []
```

That uploaded all my 2020 albums, _but_ also ended up matched some thumbnails that were generated by some desktop photo management programs, which I then deleted manually from google photos.

Now I update my configuration to upload 2019 as well:

```
includePatterns: ["2020*", "2019*"]
excludePatterns: ["*modified*", "*eaDir*", "*DS_Store*"]
```

I'm _pretty confident_ these patterns will work, but my only way to test it is to try it.

If I could `./gphotos-uploader-cli push --dry-run`, it could just print something like this:

```
My plan is to upload the following files:
  /path/to/photo/dir/20191011-an-older-album/1.jpg
  /path/to/photo/dir/20191011-an-older-album/2.jpg
  ...and so on

and to create the following albums with these contents:

  20191011-an-older-album
     /path/to/photo/dir/20191011-an-older-album/1.jpg
     /path/to/photo/dir/20191011-an-older-album/2.jpg
```

...and that helps me be confident that my inclusions and exclusions are working as I expect.

**Comment by aaronjanse** [comment]
Jumping on the feedback train, I agree: this tool is fantastic. I'm using it to migrate my photos from one Google account to another (via Google Takeout). Thank you!

**Comment by pacoorozco** [comment]
Dry run is going to be followed in #216
