### ISSUE TITLE
Add dry run on push command

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#216]
In behalf of @grumpyjames:

Rather than actually calling the photos API, it would just tell you what it would do.

This can be useful to test changes to the `includePatterns` and `excludePatterns`.

An example:

I am slowly been working my way through my photo archive. My directories start with the year in which the photos were taken, so like this:
```
20200302-album-one
20200103-another-album
20191011-an-older-album
```
Using the tool for the first time, my config looked like this:
```
includePatterns: ["2020*"]
excludePatterns: []
```
That uploaded all my 2020 albums, but also ended up matched some thumbnails that were generated by some desktop photo management programs, which I then deleted manually from google photos.

Now I update my configuration to upload 2019 as well:
```
includePatterns: ["2020*", "2019*"]
excludePatterns: ["*modified*", "*eaDir*", "*DS_Store*"]
```
I'm pretty confident these patterns will work, but my only way to test it is to try it.

If I could `./gphotos-uploader-cli push --dry-run`, it could just print something like this:
```
My plan is to upload the following files:
  /path/to/photo/dir/20191011-an-older-album/1.jpg
  /path/to/photo/dir/20191011-an-older-album/2.jpg
  ...and so on
```
and to create the following albums with these contents:
```
  20191011-an-older-album
     /path/to/photo/dir/20191011-an-older-album/1.jpg
     /path/to/photo/dir/20191011-an-older-album/2.jpg
```
...and that helps me be confident that my inclusions and exclusions are working as I expect.

Coming from #214

**Comment by pacoorozco** [comment]
Grouping items into albums is a bit more difficult, but `--dry-run` could bring this output easily:

```
$ ./gphotos-uploader-cli  push --dry-run
Enter the passphrase to open the token store: 
[info]   Found item to upload: '/home/Test/test/test1/IMG_20140227_215903.jpg' to album: 'test1'
[info]   Found item to upload: '/home/Test/test/test1/RelampagoAkademy2013.webm' to album: 'test1'
[info]   Found item to upload: '/home/Test/test/test1/Screenshot 2020-07-11 14.07.39.png' to album: 'test1'
[info]   Found item to upload: '/home/Test/test/test1/Screenshot 2020-07-30 22.28.22.png' to album: 'test1'
[info]   4 files pending to be uploaded in folder '/home/Test/test'.
[info]   4 processed files: 4 successfully, 0 with errors
```

**What do you think @grumpyjames?**

**Comment by grumpyjames** [comment]
That is perfect, thank you!
