### ISSUE TITLE
Download feature

### ISSUE THREAD

**Issue by haritux** [gphotosuploader/gphotos-uploader-cli#218]
**Is your feature request related to a problem? Please describe.**
New feature

**Describe the solution you'd like**
Would have been great if this has got a DOWNLOAD option as well. Or may be a real-time 2 way sync that provides Folder/File hierarchy cusomisation so that the Album names are and folder names look like exact mirror, not like photos/albums/yyyymm thing.

**Describe alternatives you've considered**
About to try https://github.com/gilesknap/gphotos-sync 

**Additional context**
N/A

**Comment by pacoorozco** [comment]
Hi @haritux 

Thanks a lot for sharing this feature request. This project was initiated to work on file uploading, that is where the current name is coming from. 

But who knows how it will evolve 😅

**Comment by pacoorozco** [comment]
Please, take a look to #231

**Comment by richtong** [comment]
It would be great to allow download as well, there are two barely completed projects that just about do this, does the original photoslibrary still exist, it looks like this is now your own go client, but does the download pieces
