### ISSUE TITLE
Error 400: Request must contain a valid upload token., badRequest

### ISSUE THREAD

**Issue by gregbert42** [gphotosuploader/gphotos-uploader-cli#223]
This had been working for quite a while, but i noticed it stopped working several months ago. I tried to re initialize and refresh the token several times, but i keep getting this error. I am using the dockerized version. I go through the authentication procedure (docker exec -it gphotos-uploader run), which is successful and gives me a green screen of success. 
Any idea what i might be doing wrong?

```
[info]   Found item to upload: /photos/2020/09/02/IMG_3293.JPG (many lines like this...)
[info]   4708 files pending to be uploaded in folder '/photos'.
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/.mounted, err=googleapi: Error 400: Request must contain a valid upload token., badRequest
[fail] X Error processing /photos/.mounted
```

Config:
```
{
  SecretsBackendType: auto,
  APIAppCredentials: {
    ClientID:     "redacted.apps.googleusercontent.com",
    ClientSecret: "redacted",
  }
  jobs: [
    {
      account: myemail@gmail.com
      sourceFolder: /photos
      makeAlbums: {
        enabled: false
        use: folderName
      }
      deleteAfterUpload: false
      uploadVideos: true
      includePatterns: []
          excludePatterns: []
    }
  ]
}

```

I am using tag: amd64-latest as of 2020 Sept 3 (not sure where to see version)

**Comment by pacoorozco** [comment]
Hi,
It seems that it has nothing related with the authentication. The `token` that is mentioned in the error is related with not being able upload the file to Google Photos.

This could happen for several reasons... can you run the CLI with `--debug` flag?

Paco

**Comment by gregbert42** [comment]
I ran push with the --debug flag.

it has a lot of photos to go through, but I see it is doing something (where before it looked like it just stalled). No additional information as to what that error is about though!

```
[info]   Found item to upload: /photos/2020/09/05/IMG_3326.JPG
[info]   Found item to upload: /photos/2020/09/05/IMG_3327.JPG
[info]   Found item to upload: /photos/2020/09/05/IMG_3328.JPG
[info]   Found item to upload: /photos/2020/09/05/IMG_3329.JPG
[info]   4643 files pending to be uploaded in folder '/photos'.
[debug]  Worker #2 processing: /photos/2019/04/22/IMG_9554.MOV
[debug]  Worker #5 processing: /photos/2019/04/22/IMG_9567.JPG
[debug]  Worker #4 processing: /photos/2019/04/22/IMG_9557.JPG
[debug]  Worker #3 processing: /photos/2019/04/22/IMG_9558.JPG
[debug]  Worker #1 processing: /photos/.mounted
[error]  error while trying to create this media item, err=unexpected error response: file=/photos/.mounted, err=googleapi: Error 400: Request must contain a valid upload token., badRequest
[fail] X Error processing /photos/.mounted
[debug]  Worker #1 processing: /photos/2019/04/22/IMG_9559.JPG
[debug]  Worker #4 processing: /photos/2019/04/22/IMG_9560.JPG
[debug]  Successfully processing /photos/2019/04/22/IMG_9557.JPG
[debug]  Worker #3 processing: /photos/2019/04/22/IMG_9562.JPG
[debug]  Successfully processing /photos/2019/04/22/IMG_9558.JPG
[debug]  Successfully processing /photos/2019/04/22/IMG_9567.JPG
[debug]  Worker #5 processing: /photos/2019/04/22/IMG_9553.JPG
[debug]  Worker #1 processing: /photos/2019/04/22/IMG_9602.JPG
[debug]  Successfully processing /photos/2019/04/22/IMG_9559.JPG
[debug]  Worker #4 processing: /photos/2019/04/22/IMG_9569.JPG
[debug]  Successfully processing /photos/2019/04/22/IMG_9560.JPG

```

**Comment by gregbert42** [comment]
ok. clearly its uploading. Would it benefit from a non-debug activity indicator?

**Comment by srgvg** [comment]
I'm noticing this error, too, but it seemed to be at the beginning of a run at first, and leter it showed it uploaded.

Sample of debug logs:

```
Sep 10 16:41:03 [error]  error while trying to create this media item, err=unexpected error response: file=~/Photos2Google/2008/08/23/img_8609.jpg, err=googleapi: Error 400: Request must contain a valid upload token., badRequest
Sep 10 16:41:03 [fail] X Error processing ~/Photos2Google/2008/08/23/img_8609.jpg
Sep 10 16:41:03 [debug]  Worker #2 processing: ~/Photos2Google/2008/08/23/img_8610-1.jpg
```

Then I noticed, it seemed to repeat with the same files. When I tried checking those files, and viewing them, I got these warnings:

With `feh` image viewer:

```
feh WARNING: ~/2008/08/23/img_8551.jpg - No Imlib2 loader for that file format
```

Opening the folder with `Nemo` file browser:
```
** (gdk-pixbuf-thumbnailer:910155): WARNING **: 16:43:55.957: Could not thumbnail 'file:///~/Photos2Google/2008/08/23/img_8584-1.jpg': Couldn?t recognize the image file format for file ?/home/serge/scratch/Photos2Google/2008/08/23/img_8584-1.jpg?
```

Opening with `eog`:
![20200910164618](https://user-images.githubusercontent.com/382239/92748225-385c6280-f385-11ea-8f34-5e72753877d6.png)

So this seems to be a problem within the file, where `gphotouploader` doesn't return a proper error, I think.

Note that `feh` manages to display the image, only yielding said warning. `nemo` doesn't show a thumbnail though, and as shown, `eog` doesn't display it, too. AFAICS, the Google Photo API refuses the picture. If there is a way to still upload it, and somehow force the api to accept it,  that would be nice though.

**Comment by pacoorozco** [comment]
@srgvg , the file you are trying to upload is corrupted, that's why `feh` or `nemo` are not able to open it. 

Google Photos API doesn't allow to add it to the library, that's why `gphotos-uploader-cli` is showing you the error. 

The same apply to @gregbert42 , you were trying to upload `/photos/.mounted` that it's not a allowed file format in Google Photos. You can use `includePatterns` and `excludePatterns` to exclude them.

**Comment by gregbert42** [comment]
Thanks @pacoorozco - i recognized that, which is why I closed this issue. But i did suggest perhaps a progress indicator of some kind, which would have saved me thinking the thing was dead after that error. thank you very much for your work.
