### ISSUE TITLE
Remove all uploaded photos.

### ISSUE THREAD

**Issue by alix-artus** [gphotosuploader/gphotos-uploader-cli#225]
**Is your feature request related to a problem? Please describe.**
I messed up when I set up how to build album names from folder (I used _ for separators but that does not work well with the search in Google Photos). Now, I have more than 200 albums with the wrong names. I could change them one by one but that will be a lot of work.

**Describe the solution you'd like**
I would like a way to remove all uploaded photos to be able to start over.

**Describe alternatives you've considered**
I have considered manually changing the 200 album names using the web user interface.

**Comment by pacoorozco** [comment]
I think it should be enough if we remove only the albums.

So, you remove the albums, pictures are there without being assigned to an album, then you re-upload the files and they will be assigned to the new albums. Google Photos prevents to keep the same file twice, even you have to uploaded again.

What do you think?

**Comment by pacoorozco** [comment]
Please, take a look to #231

**Comment by alix-artus** [comment]
Yes, removing albums would be a great solution.
