### ISSUE TITLE
Should we remove support for multiple accounts?

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#231]
Currently `gphotos-uploader-cli` supports several Google Accounts at the same time. It means that you can configure the CLI to upload your pictures to different accounts in the same run. 

This could be a really cool feature, but I have the feeling that nobody is using it, and **it's making more difficult to enable some other features** (like headless, configuration by env vars, album management...). 

In fact, this feature is blocking us to move `gphotos-uploader-cli` to a different level, where it could grow as a full **Google Photos manager**.

So, my question to you is... **Should multi-account support be removed from `gphotos-uploader-cli`?**

> Please, use :+1: or :-1: to add your feedback, and feel free to share more context if you want.

**Comment by eGit** [comment]
I never used this feature.

What I would be interested in though would be an option to have multiple accounts and then have a way to choose when starting the upload which one to use. Is there already a Wiki entry or something explaining how to do this best?

**Comment by pacoorozco** [comment]
Hi @eGit 

This could be done using the flag `--config`. See how to use it `gphotos-uploader-cli --help`.

**Comment by alix-artus** [comment]
I never use multiple accounts. It seems to me that, if one wants to use multiple accounts, then this can be scripted with bash or zsh and the `--config` flag, as you have suggested.

**Comment by pacoorozco** [comment]
Multiple accounts support has been removed:
```
{
  APIAppCredentials:
  {
    ClientID: 844831818923-b6ogvci0fmmcfqmndljj54fovvtjfpqr.apps.googleusercontent.com
    ClientSecret: REMOVED
  }
  Account: pakusland@gmail.com
  SecretsBackendType: file
  Jobs:
  [
    {
      SourceFolder: ~/src/gphotos-uploader-cli-test/data
      MakeAlbums:
      {
        Enabled: true
        Use: folderName
      }
      DeleteAfterUpload: false
      IncludePatterns: []
      ExcludePatterns: []
    }
  ]
}
```
