### ISSUE TITLE
How to use different configs

### ISSUE THREAD

**Issue by crotoc** [gphotosuploader/gphotos-uploader-cli#240]
Thanks for the great project and save me a lot of time! 👍 

I have two photo directories:
For one of them, I want to create album using subdirectory names. 
But for the other, I just want to upload the phtotos WITHOUT creating albums. 
I can write to two config files separately for the two directories but how can I specify the config file and do the uploading? Thanks!

**Comment by pacoorozco** [comment]
Try `gphotos-uploader-cli --help`, the flag you're looking for is `--config`. We are working to improve the documentation in a site.

**Comment by crotoc** [comment]
Got it! I need to create different dirs for each config and specify each dir using --config! Thanks!
