### ISSUE TITLE
Error met while uploading about 10k photos

### ISSUE THREAD

**Issue by crotoc** [gphotosuploader/gphotos-uploader-cli#241]
Thanks for creating this great tool!
I am trying to upload 10k photos and automatically create album using dir names. Every serval seconds, I encountered this kind of error warning:

error while trying to create this media item, err=rate limit reached. wait ~30 seconds before trying again

How can I avoid it? Thanks

**Comment by pacoorozco** [comment]
Hi @crotoc 

Google Photos apply a [API limit quota](https://developers.google.com/photos/library/guides/api-limits-quotas), you can read it on the [README](https://github.com/gphotosuploader/gphotos-uploader-cli) too.

**Comment by crotoc** [comment]
![Screenshot_20201006_104151_com android chrome](https://user-images.githubusercontent.com/12446554/95224681-93d11300-07c0-11eb-9f3b-7ebe7d5a3ad8.jpg)

**Comment by pacoorozco** [comment]
I think you are not reaching these two quotas, but there are others such the ones that they are stating on the documentation

> In addition to these limits there are other quotas that exist to protect the reliability and integrity of our systems. If you receive a 429 error, you've likely hit one of these quotas. If you receive one of these errors, reduce the number of requests you are making over a given time period.

The CLI tries to do it by using exponential backoff, that's why yo see the messages on the log.

**Comment by crotoc** [comment]
If I encounter this error, is that mean the photos fail to upload? Will they be uploaded again after I rerun the same command? I read the documents saying that the software can upload "new" photos to save the bandwith. Thanks!

**Comment by pacoorozco** [comment]
Exactly, the file has not been uploaded, but It will be try it if you run the command again.

**Comment by crotoc** [comment]
That's great! I can do it again to make sure all photos would be uploaded. Thanks!

**Comment by crotoc** [comment]
Is it possible to limit the request number per second? My case seems like to be relevent to the quota below.

![image](https://user-images.githubusercontent.com/12446554/95253119-8d07c780-07e3-11eb-8ebc-a8297aa73b37.png)

**Comment by pacoorozco** [comment]
No, It's not possible right now... I'm working to reduce the number of queries using cache layers, but rate limit will be still handled by Google Photos
