### ISSUE TITLE
Unable to install gphotos uploader cli on Ubuntu 18.04

### ISSUE THREAD

**Issue by YousufSSyed** [gphotosuploader/gphotos-uploader-cli#242]
**Describe the bug**
gphotos-uploader-cli init doesn't do anything, and returns `gphotos-uploader-cli: command not found`

**To Reproduce**
In the Ubuntu terminal, do `sudo apt-get install golang` and `go get github.com/gphotosuploader/gphotos-uploader-cli` (I don't know how to get make build to work).

**Expected behavior**
gphotos-uploader-cli init would work

**Screenshots**

**Desktop & Client versions (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Version: gphotos-uploader-cli version

**Additional context**

**Comment by pacoorozco** [comment]
Hi @YousufSSyed 

Have you followed any of this [installation methods](https://github.com/gphotosuploader/gphotos-uploader-cli#install)? They should work for you.

**Comment by YousufSSyed** [comment]
When I try `make build`, I get this:

```
--> Building binary artifact (gphotos-uploader-cli v1.2.0)...
../go/src/github.com/gphotosuploader/gphotos-uploader-cli/internal/cmd/push.go:8:2: code in directory /home/yousuf/go/src/github.com/gphotosuploader/google-photos-api-client-go expects import "github.com/gphotosuploader/google-photos-api-client-go/v2"
main.go:6:2: use of internal package not allowed
Makefile:53: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by pacoorozco** [comment]
@YousufSSyed Are you used to build Go applications? I think you has not configured you Go environment properly.

**What if you use one of the [compiled binaries](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/latest)? ** Just download, decompress and run it.

**Comment by YousufSSyed** [comment]
If you can't tell, I don't know what I'm doing. I don't know how to run the binary either, typing in gphotos-uploader-cli in the terminal with the binary in the same directory, all I get is `"gphotos-uploader-cli: command not found"`

**Comment by pacoorozco** [comment]
1. Go to the [releases page](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/latest)
2. Download the `gphotos-uploader-cli_X_linux_amd64.tar.gz` (being X the latest version)
3. Untar the file `tar -zxf gphotos-uploader-cli_X_linux_amd64.tar.gz`.
4. Execute the binary `./ghotos-upload-cli --help` (see that starts with `./`)
5. Enjoy it

**Comment by YousufSSyed** [comment]
Thanks! I got it working now.

**Comment by cl0h** [comment]
If you had  followed the docs to build from source then you only need to add ./ 
./gphotos-uploader-cli init works
