### ISSUE TITLE
Date, time not set for videos

### ISSUE THREAD

**Issue by sixtybi** [gphotosuploader/gphotos-uploader-cli#251]
If I upload MTS video from web uploader, the date and time will be set according to the EXIF information of the file.
But if I use gphotos-uploader-cli, this information will not be extracted and the upload date will be set.
Is there any solution for this?

**Comment by sixtybi** [comment]
I just checked, it is also not set for mp4 video files. But it works for pictures.

**Comment by pacoorozco** [comment]
Hi,

As it's stated in the documentation, Google Photos should extract this data from the EXIF metadata. In case, for any reason, this data is not set, Google Photos will use the upload date/time. Unfortunately, the API doesn't allow us to change this date, and [It's known by Google that the EXIF data extraction is not working very well](https://support.google.com/photos/thread/131051?hl=en).

One of the workaround that they point on the previous shared post is to edit these date manually. In images works better than video, who knows why 😓

**Comment by sixtybi** [comment]
I did some expriment today, and it seems that if I set the create date in exif based on file modification date, it works. Thanks for the hint @pacoorozco
