### ISSUE TITLE
Bandwidth limit

### ISSUE THREAD

**Issue by hujuice** [gphotosuploader/gphotos-uploader-cli#254]
I am a photographer and I am very happy with gphotos-uploader-cli.
At the same time, I wok with home quality Internet connections. Or poorest, like in basic hotels or other random accommodations.
This means that during big uploads (hundreds of MB) my Internet become unusable.

Is there a way to add a bandwidth limit in the options?
(You can think to the --bwlimit option of rsync.)

Thank you very much for reading this and mostly for the useful application.
HUjuice

**Comment by pacoorozco** [comment]
Hi @hujuice 

Thanks for using and giving feedback!

The bandwidth limitation is a very complex feature. It should force us to implement something at network layer, that is probably to far away from where we are most comfortable. Said that, you can try to avoid the bandwidth used by this application reducing the number of workers `--workers` flag.

Another approach, the one I've used in other scenarios, is to use a [bandwidth limiter](https://www.comparitech.com/net-admin/best-bandwidth-limiter-tools/)

**Comment by hujuice** [comment]
Thank you Paco
I don't know go and I don't know the API, so I tried. I am going to use the kernel cgrops feature.
Another option could be to rsync --bwlimit the photos to a VPS, and then run gphotos-uploader-cli fron there, but I couldn't register the application without a browser. There's no way to do this?

Sergio

**Comment by pacoorozco** [comment]
Hi
You can register the application without a browser (you can use a browser in a different computer).

Following the [Getting started guide](https://gphotosuploader.github.io/gphotos-uploader-cli/#/getting-started?id=first-time-run) you can open the URL in a different computer. An the end of the process you can copy the authorisation code on your VPS.

**Comment by hujuice** [comment]
Well, it appears to work, finally.
I'm using "SecretsBackendType: file" and I used the environment variable GPHOTOS_CLI_TOKENSTORE_KEY at the first run. Now it's working even when GPHOTOS_CLI_TOKENSTORE_KEY is empty.
Nice!
The Google API credentials are always a mess for me.
Thank you very much!
