### ISSUE TITLE
Very minor: add a info line after entering the oauth passphrase

### ISSUE THREAD

**Issue by hujuice** [gphotosuploader/gphotos-uploader-cli#260]
What I propose is very minor, so minor that I feel disturbing, but I notice the same every time.
After entering the passphrase, there are two possibilities: one is '[info]   Token has been expired, refreshing', the other one is... nothing. Quite often I hit the Enter/Return key again to be sure that I didn't miss the first hit.
Any info line, in one of the next versions, like '[info]   Token is valid', should be comfortable.

I don't know the go syntax, so I can't submit a fix.
It should be something in internal/app/oauth.go, after the 44 case. In my imaginary code it could be like
```
case token.Valid():
    app.Logger.Info("Token is valid")
```

Thank you very much
Sergio

**Comment by pacoorozco** [comment]
When you run the command and get the token a log line is shown:
```
[info]   Reading configuration from 'config/config.hjson'
[info]   Getting OAuth token for 'pakusland@gmail.com'
Enter the passphrase to open the token store: 
[done] √ Token is valid, expires at 2021-01-08 11:12:57.712972753 +0100 CET m=+3602.393897200
[info]   Found 24 items to be uploaded processing location '/home/paco/src/gphotos-uploader-cli-test/data'.
[info]   Running in dry run mode. No changes has been made.
```
