### ISSUE TITLE
Error when using code in master branch

### ISSUE THREAD

**Issue by worjak** [gphotosuploader/gphotos-uploader-cli#265]
So I got the app build (thanks for excelent guidance) and updatede the configure.json. So I think im ready to first run, but gets "panic: runtime error: invalid memory address or nil pointer dereference" and son on... 

`jaw@wormnethub:~/gphotos-uploader-cli$ ./gphotos-uploader-cli push --config ~/.gphotos-uploader-cli/
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x83bcf9b]

goroutine 1 [running]:
github.com/gphotosuploader/gphotos-uploader-cli/internal/app.(*App).Stop(0x8c566c0, 0x8c346c0, 0x0)
        /home/jaw/gphotos-uploader-cli/internal/app/app.go:80 +0x6b
github.com/gphotosuploader/gphotos-uploader-cli/internal/cmd.(*PushCmd).Run.func1(0x8c566c0)
        /home/jaw/gphotos-uploader-cli/internal/cmd/push.go:51 +0x21
panic(0x846eec0, 0x87bdb00)
        /usr/lib/go-1.15/src/runtime/panic.go:969 +0x15c
github.com/gphotosuploader/gphotos-uploader-cli/internal/app.(*App).NewOAuth2Client(0x8c566c0, 0x855d6a0, 0x8c9c010, 0x20, 0x8c566c0, 0x0)
        /home/jaw/gphotos-uploader-cli/internal/app/oauth.go:35 +0xce
github.com/gphotosuploader/gphotos-uploader-cli/internal/cmd.(*PushCmd).Run(0x8c0e170, 0x8d86280, 0x8c0e200, 0x0, 0x2, 0x0, 0x0)
        /home/jaw/gphotos-uploader-cli/internal/cmd/push.go:60 +0xf8
github.com/spf13/cobra.(*Command).execute(0x8d86280, 0x8c0e1d0, 0x2, 0x2, 0x8d86280, 0x8c0e1d0)
        /home/jaw/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x313
github.com/spf13/cobra.(*Command).ExecuteC(0x87c1800, 0x0, 0x1, 0x804e691)
        /home/jaw/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x257
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jaw/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/gphotosuploader/gphotos-uploader-cli/internal/cmd.Execute()
        /home/jaw/gphotos-uploader-cli/internal/cmd/root.go:53 +0x27
main.main()
        /home/jaw/gphotos-uploader-cli/main.go:10 +0x1a
jaw@wormnethub:~/gphotos-uploader-cli$`

**Comment by worjak** [comment]
Adding the ---debug flag gives this:

`jaw@wormnethub:~/gphotos-uploader-cli$ ./gphotos-uploader-cli push --config ~/.gphotos-uploader-cli/ --debug
[debug]  Reading configuration from '/home/jaw/.gphotos-uploader-cli/config.hjson'
[debug]  Getting OAuth token for jakob.worm@gmail.com
[debug]  Shutting down File Tracker service...
panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by pacoorozco** [comment]
Hi

You are right... there's a big in the current master... I'm working to launch a new version and by mistake I've modified the master branch

```
$ git fetch --all --tags
$ git checkout tags/v2.0.0 v2.0.0
$ make clean
$ make build
```

Or download the [latest binary here](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/latest)

**Comment by worjak** [comment]
Great! This got me moving:

`
$ git fetch --all --tags
$ git checkout tags/v2.0.0 -b v2.0.0
$ make clean
$ make build
`
