### ISSUE TITLE
Add EXIF to (old) images to indicate the shot timestamp

### ISSUE THREAD

**Issue by pjsg** [gphotosuploader/gphotos-uploader-cli#267]
Old cameras and scanners etc do not have a sensible EXIF data blob in images. In particular, the time of the image is not set correctly.

I'd like to see gphotos-uploader insert an exif blob in these cases when the short time can be parsed out of the filename. I'd like to be able to specify an ordered list of layout strings to be matched against the full pathname. [I'm not sure if this is enough power, or whether some extra pattern matching is required.]. This should be coupled with an option to *not* upload images if the date cannot be determined.

The other approach, which is probably simpler, would be to allow gphotos-uploader to read a file which contains the metadata for some set of images to be uploaded, and then just mash that metadata into the EXIF blob as part of the upload.

I could run a standalone tool over my local library and modify all the files before upload, but I'm nervous about damaging my library (which is quite large). This would be the reason to emit a metadata file which lists the relevant metadata for each image.

If this is seen as a reasonable idea, then I'd have a go at implementing it.

**Comment by pacoorozco** [comment]
Hi @pjsg 

Thanks for sharing your idea... I'm not sure if it would be a feature request supported by too many users. The two approaches which you were sharing looks too complex to me, maybe because I don't have the problem you were mentioning.

**Comment by LegoChicken** [comment]
Hi @pjsg I think this outside the scope of an uploader. However, there are tools you could use in Linux (or Windows) to set the EXIF information from the filename. I've used ExifTool (https://exiftool.org/) to set the filename from the EXIF. I think it likely that you could use ExifTool to do the reverse of setting the EXIF information from the filename.
