### ISSUE TITLE
It is not clear which image types are uploaded/included by default

### ISSUE THREAD

**Issue by homiak** [gphotosuploader/gphotos-uploader-cli#283]
In the documentation the following is stated: 
`If includePatterns is empty, _IMAGE_EXTENSIONS_ will be used.`
and further down _IMAGE_EXTENSIONS_ lead to this URL https://support.google.com/googleone/answer/6193313#zippy=%2Ctypes-of-raw-files-you-can-back-up%2Cwhat-you-need-to-back-up-photos-videos

That page does not clarify which image type are actually supported/uploaded. 
For example, experimentally I found that `.ARW` files are not actually uploaded by default, even though the google support page that you reference in the docs mention the support for Sony cameras raw format which is .ARW. 
In my case files had uppercase extension. I can upload these files without any issues but I have to use include pattern defining the extension explicitly. (like **/*.ARW)

This happens under Mac OS 10.15.7 
Version gphotos-uploader-cli v3.0.0-alpha1

**Comment by pacoorozco** [comment]
Hi @homiak 

The list of files that `_IMAGE_EXTENSIONS_` include is [that](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/f921dcde70f4f97997e17f1091ec491d824d7c61/internal/filter/patterns.go#L11).

It's the list of file formats described on the first section of the link that the documentation points to, [this](https://support.google.com/googleone/answer/6193313#zippy=%2Ctypes-of-raw-files-you-can-back-up%2Cwhat-you-need-to-back-up-photos-videos).

If you provide the list of file extensions for the **RAW files** I can create a new pattern: `_IMAGE_RAW_EXTENSIONS_` . I don't have knowledge to compile this list.

You can, alternatively, include the desired file extensions using `includePatterns`:

```
includePatterns: [ "_IMAGE_EXTENSIONS_", "**/*.ARW" ]
```

What do you think?

**Comment by homiak** [comment]
I am happy with an explanation, thank you. I think you just need to fix the documentation so that it's clear what _IMAGE_EXTENSIONS_ includes. I would also recommend you to make the list of extensions case insensitive. Many cameras write image/video files in all capital letters so I got surprised when using _ALL_VIDEO_FILES_ pattern collection my *.MP4 files were not included.

**Comment by pacoorozco** [comment]
Hi again!

- The [documentation](https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration?id=tagged-patterns) has been updated.
- `_RAW_EXTENSIONS_` was already existing. 😓 
- All patterns are going to be case in-sensitive (good suggestion).

**Comment by homiak** [comment]
Thanks! I think it's pretty clear now. Except "file extensions case in-sensitively" phrase is a bit confusing. I would say "file extensions are case insensitive" or "file extensions are matched case insensitively" or maybe ask your native English speaking colleague for a better sentence. Also, maybe give an example to avoid any confusion. Thank you

**Comment by homiak** [comment]
Also, is it possible to combine _RAW_EXTENSIONS_ and _IMAGE_EXTENSIONS_? It's not clear from the documentation.

**Comment by pacoorozco** [comment]
Yes it is, they are treated as `patterns`... so it's fine to use:
```
includePatterns: [ "_IMAGE_EXTENSIONS_", "_RAW_EXTENSIONS_" ]
```

**Comment by pacoorozco** [comment]
Case insensitive patterns is not merged yet. This issue will be close once patched version is on production
