### ISSUE TITLE
Add support to Windows

### ISSUE THREAD

**Issue by homiak** [gphotosuploader/gphotos-uploader-cli#284]
I can see there is no mention of WIndows in the documentation. Go itself can be compiled to windows. Are you using any libraries that are incompatible? I think gphotos-uploader-cli is an excellent tool, and it would have much wider adaptation if Windows is supported.

**Comment by pacoorozco** [comment]
Hi, 

Unfortunately,  we are using some libraries that didn't work in Windows. As far as I know there are at least two packages that are not compatible. 

And eve more, I've not tested it under Windows. Google Photos offers a client for Windows and Mac, that's the reason behind not supporting Windows. 

But we can create a feature request to support it.

**Comment by homiak** [comment]
>Google Photos offers a client for Windows and Mac, that's the reason behind not supporting Windows.

Do you mean Backup and Sync? The major issue with it is that it does not support creating albums, it just syncs media in bulk. This gives gphotos-uploader-cli a big advantage in my view. The bulk of computer users are still on Windows so it makes total sense to support it. Can you list the libraries that are not supported on WIndows? Unfortunately I am not a Windows user myself, but I will try to see what can be done to make gphotos-uploader-cli  work on Windows.

**Comment by pacoorozco** [comment]
It's not exhaustive but we should review:

- github.com/bmatcuk/doublestar/v2 
- github.com/facebookgo/symwalk 
- github.com/mitchellh/go-homedir 

And probably some code that is using fixed folder separators.

**Comment by homiak** [comment]
If I make a PR to replace these and other windows incompatible libraries, would you be willing to take a look at it and potentially merge it, providing of cause the change does not break anything? In other words - would you be happy to support WIndows as well?

**Comment by pacoorozco** [comment]
I've been reviewing the libraries and I think they could be easy to update to support Windows... 

Feel free to create a PR, please follow the CONTRIBUTING guide and add some tests in Windows, given that I'm not using it at all. 

At the end, this is a OS project, so collaborations are very welcomed.
