### ISSUE TITLE
'invalid_grant' error when trying to authenticate with google app domain

### ISSUE THREAD

**Issue by mikeller** [gphotosuploader/gphotos-uploader-cli#287]
**Describe the bug**
When trying to authenticate for the gphotos-uploader-cli with a google account that is part of an app domain, an 'invalid_grant' error is thrown. This used to be working previously (on version 1.0.4), but it is producing the same error now.

**To Reproduce**

Run `gphotos-uploader-cli auth`.

**Actual behavior**
An error is returned:

```
mikeller@pc:/opt/gphotos-uploader$ /opt/gphotos-uploader/gphotos-uploader/gphotos-uploader-cli auth
[info]   Reading configuration from '/home/mikeller/.gphotos-uploader-cli/config.hjson'
[info]   Getting OAuth token for 'mikeller@<appdomain>.ch'
[error]  Unable to refresh the token, err: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
[fatal]  unable to refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

**Expected behavior**
A prompt to go to the authorisation URL in a browser, like

```
Visit the following URL in your browser:
https://accounts.google.com/o/oauth2/auth?...
```

**Desktop & Client versions (please complete the following information):**
 - Operating System: ubuntu 21.04
 - Version: https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v3.0.1

**Additional context**
- this used to be working previously, using version 1.0.4, but it is producing the same error as 3.0.1 now - seems to be a change on Google's side;
- testing the same setup with an @gmail.com address works for `gphotos-uploader-cli auth` and returns the 'Visit the following URL' prompt.

**Comment by pacoorozco** [comment]
Hi @mikeller 

I've just tested it and it's working well...
```
./gphotos-uploader-cli --config ~/gphotos2 auth
[info]   Reading configuration from '/home/paco/gphotos2/config.hjson'
[info]   Getting OAuth token for 'pakus@-----------.net'

Visit the following URL in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=98-------8-0qfr0nj94gi------mjg3ee7b4kmdk.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary&state=state

After completing the authorization flow, enter the authorization code here: 
[done] √ Token is valid, expires at 2021-02-22 12:17:31.329486071 +0100 CET m=+3626.735166655
Enter the passphrase to open the token store: 
[done] √ Successful authentication for account 'pakus@-----------.net'
```
**Can you review the configuration of your domain?** Try to follow [this documentation](https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration?id=apiappcredentials) again.

**Comment by pacoorozco** [comment]
@mikeller Have you tested it again?

**Comment by mikeller** [comment]
Hi @pacoorozco.

Sorry, for some reason I did not get a notification for your last comment.

I have tried it again, still the same:

```
mikeller@pc:~/git/betaflight$ /opt/gphotos-uploader/gphotos-uploader/gphotos-uploader-cli auth
[info]   Reading configuration from '/home/mikeller/.gphotos-uploader-cli/config.hjson'
[info]   Getting OAuth token for 'mikeller@<domain>.ch'
[error]  Unable to refresh the token, err: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
[fatal]  unable to refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

And I have reviewed the configuration for the app authorisation - it looks correct, and the fact that I can authenticate with a Google account that is outside of the domain for the same `APIAppCredentials` suggests that this is correct.

Is there any setting in the Google app domain itself that needs to be set in order to give users inside the domain the permissions to access this app?

**Comment by pacoorozco** [comment]
Hi @mikeller 

I don't think so! If you have created the app in Google (with the needed credentials) I should be enough. Maybe you can review Google Cloud logs to see why the authorization is not working as expected.

In my GSuite domain it's working without adding anything else.

**Comment by mikeller** [comment]
Ok, looks like the `invalid_grant` (which seems to be Google's default response for 'something has failed with oauth') was a red herring.
In the end it turned out that the credentials stored in gnome-keyring had expired, but the call to `gphotos-uploader-cli auth` tried to re-use them anyway:

```
[info]   Getting OAuth token for 'mikeller@<domain>'
[debug]  Token has been expired, refreshing it...
[error]  Unable to refresh the token, err: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
[fatal]  unable to refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

Removing the credentials from gnome-keyring fixed this:

```
[info]   Getting OAuth token for 'mikeller@<domain>'
[debug]  Unable to retrieve token from token manager: token was not found
```

Not sure if the behaviour should be to ignore / discard any stored credentials when `gphotos-uploader-cli auth` is called, or if there should be a `force-auth` or similar command line argument for this.
