### ISSUE TITLE
Album not being created / null album name?

### ISSUE THREAD

**Issue by sandeen** [gphotosuploader/gphotos-uploader-cli#288]
With `"CreateAlbums":"folderName"` set (folderPATH too) I don't seem to get albums created:

```
[debug]  Current configuration: {"APIAppCredentials":{"ClientID":"XXX.apps.googleusercontent.com","ClientSecret":"REMOVED"},"Account":"X@gmail.com","SecretsBackendType":"auto","Jobs":[{"SourceFolder":"/mnt/media/Misc/DIRECTO4","CreateAlbums":"folderName","DeleteAfterUpload":false,"IncludePatterns":["**/*.jpg","**/*.png"],"ExcludePatterns":[]}]}
[info]   Getting OAuth token for 'XXX@gmail.com'
Enter the passphrase to open the token store: 
[done] √ Token is valid, expires at 2021-02-23 11:15:59.854538049 -0600 CST
[debug]  Worker #1 is starting
[debug]  Upload file '/mnt/media/Misc/DIRECTO4/DIRECTO-0010.png' to album ''.
[debug]  Upload file '/mnt/media/Misc/DIRECTO4/DIRECTO-0011.png' to album ''.
[debug]  Upload file '/mnt/media/Misc/DIRECTO4/DIRECTO-0037.png' to album ''.
[info]   Found 3 items to be uploaded processing location '/mnt/media/Misc/DIRECTO4'.
```

Is this a bug or have I done something wrong?

**Comment by pacoorozco** [comment]
Hi

The CLI will create the albums based on the folder name where the files is. Reviewing your configuration, your files are on the root of your source folder. That's why no album is created. 

If you want to create an album for these files:
1. Create a folder inside your current source folder
2. Move your local files to this folder
3. Run the `gphotos-upload-cli`

**Comment by sandeen** [comment]
Ahhh I see.  Sorry about that!  I thought that the folder/directory containing the images always created the album name, and did not realize that it required a subdir under the source dir.  But that makes much more sense now.

Perhaps this can be clarified in the docs:

> `folderName` will use the name of the folder, where the item is uploaded from, to set the album name.

perhaps as something like:

> `folderName` will use the name of the folder within the `SourceFolder`, where the item is uploaded from, to set the album name.

Because I thought it took the parent directory name as album name in all cases, even if it was the SourceFolder.  But it makes total sense now.

Thanks for your help,
-Eric

**Comment by pacoorozco** [comment]
I've updated the documentation... thanks
