### ISSUE TITLE
[fatal]  invalid configuration at '[...]/config.hjson': option SecretsBackendType is invalid, 'auto,'

### ISSUE THREAD

**Issue by eGit** [gphotosuploader/gphotos-uploader-cli#289]
Error since updating to 3.0.1

config.hson works with 1.2.0 and 2.0.1

> {
  SecretsBackendType: auto,
  APIAppCredentials: {
    ClientID:     "censored",
    ClientSecret: "censored",
  }
  jobs: [
    {
      account: censored@gmail.com
      sourceFolder: '/mnt/censored'
      makeAlbums: {
        enabled: true
        use: folderName
      }
      deleteAfterUpload: true
      uploadVideos: true
      includePatterns: [ "_ALL_FILES_" ]
	  excludePatterns: []
    }
  ]
}

**Comment by pacoorozco** [comment]
Hi

Please review the [CHANGELOG](https://www.github.com/gphotosuploader/gphotos-uploader-cli/tree/main/CHANGELOG.md) or the documentation. Version 3.x is not backward compatible.

You need to adapt your config

**Comment by eGit** [comment]
Thanks. I did read the documentation before posting but I guess I didn't fully understand the changes. Now it seems to work.

**Comment by pacoorozco** [comment]
No problem... I'm glad to know that it's working now :-P

**Comment by eGit** [comment]
Maybe you should add a short section in the documentation called "Config changes 3.x and later". Or maybe just show a 3.x compatible config template that works after you fill in credentials, email and sourcefolder

**Comment by pacoorozco** [comment]
The last part, 3.x compatible config is already on the documentation [here](https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration)
