### ISSUE TITLE
Exit gracefully when hitting 10.000 requests/day quota

### ISSUE THREAD

**Issue by Nic0w** [gphotosuploader/gphotos-uploader-cli#290]
**Is your feature request related to a problem? Please describe.**
Currently when quota is hit, gphotos-uploader-cli tirelessly retries 5 times for every photo; plus the error message isn't very informative.

**Describe the solution you'd like**
Depending on/if Google returns a meaningful error code/message for hitting quota, I'd like for gphotos-uploader-cli to exit gracefully and warn the user it's exiting because quota was hit. 

**Describe alternatives you've considered**
Upon investigating the issue I realized the cause of the messages were because of quotas and I force-killed gphotos-uploader-cli.

**Additional context**
I've got a big library of +30k photos that I'm trying to upload. I let gphotos-uploader-cli work overnight only to discover this morning it spent half the night retrying despite having hit quota.

**Comment by pacoorozco** [comment]
Hi @Nic0w 

Did you run `gphotos-uploader-cli` using debug mode? It will give you a clearer message about hitting quota. 

It's still true, that one the quota is hit. `gphotos-uploader-cli` uses exponential back-off (instead of dying). It's following [best practices](https://developers.google.com/photos/library/guides/api-limits-quotas) published by Google Photos service. 

It will not be difference between dying after quota is reached or trying it. right? What would be the benefit of exiting instead of re-trying?

**Comment by Nic0w** [comment]
Hi @pacoorozco,

Thanks for your answer :)

No, I am not running `gphotos-uploader-cli` in debug mode. That's nice to know that it can give more infos about hitting quota !
I read about the exponential back-off thing but it was my understanding that that was triggered when hitting the rate limit, not the quota limit. It might be because it made more sense to me that way.

So you ask :

> What would be the benefit of exiting instead of re-trying?

Well, my answer would be, what is the benefit of retrying ? indeed, from what I'm seeing in the logs, when `gphotos-uploader-cli` hits quota, it:

-  tries 5 times to upload a picture, possibly with an exponential backoff, but the timeframe seems to be quite short so it's not obvious to me.
- goes on to the next picture.
- loop until there are no more pictures to fail on.

so in the end I still have to launch `gphotos-uploader-cli` by hand to resume upload when the quota are okay again. 
In the event that quotas are reset while `gphotos-uploader-cli` is still trying, I will still have to restart by hand so that the failed pictures are uploaded.

There is also the screen full of error messages and Google Cloud Console showing a 52% error rate that are quite alarming things to see, and if we can avoid that, why not ?

In my opinion, it would be more useful if :

1. Without exponential back-off on hitting quota, that  `gphotos-uploader-cli` exit gracefully on first quota error. Then an human action (or a cron job at midnight PST when quotas reset) can restart the upload when possible, and no pictures are "lost", no endless error messages are shown, ...
2. With exponential back-off on hitting quota, that `gphotos-uploader-cli` keeps retrying, backing-off exponentially, on the one picture it got stuck. That way, it will reach a point in time when quotas are free again, and upload can resume normally without human assistance. Way less error messages, no "lost" pictures, no human action required on a large photo set.

**Comment by pacoorozco** [comment]
Hi @Nic0w 

Thanks for taking the time to add more context. I though you were referring to the rate limit quota and I've realized that you are referring to the storage quota 🤯 .

You're right, this error should be addressed in a different way. I created #248 some time ago to improve it. 

Unfortunately, I have not started to work on it, yet...

**Comment by Nic0w** [comment]
Hmm, I'm not talking about storage quota at all !
I'm talking about 10,000 requests per day quota, which is different from the rate limiting quota as I understand it, which would be related to not doing requests too fast, or retrying too fast on errors.

**Comment by Nic0w** [comment]
From the page you linked in your first reply :

> The quota limit for requests to the Library API is 10,000 requests per project per day.

Then there is

> In addition to these limits there are other quotas that exist to protect the reliability and integrity of our systems. If you receive a 
 429 error, you've likely hit one of these quotas. If you receive one of these errors, reduce the number of requests you are making over a given time period. For more information, refer to retrying failed requests and exponential backoff.

that refers to unspecified rate limiting, on which you should be using exponential back-off.

**Comment by pacoorozco** [comment]
Hi @Nic0w 

Ouch... I know about this quota limit for requests, but it was so high that I've never reached it. I'm always limited by the "too fast" rate limit, that's why I included the back-off.

Good news is that now we are in the same page. I agree that this quota limit of 10.000 requests/day should be treated in the same way than the storage quota. I mean, it's not retryable.

I would need to know how i can identify this response (error code, error message...) from the rest of rate limit responses (error code = 429). **Do you have an evidence of this response?** If not, I will try to create an snippet to send requests continuously and see what Google Photos answer, but If you have it It will be faster.

Thanks for taking the time to point me to the right direction 👋🏼

**Comment by pacoorozco** [comment]
This is the error code when hitting the quota:
```
googleapi: Error 429: Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:844831818923'., rateLimitExceeded
```

**Comment by Nic0w** [comment]
Hi @pacoorozco 

Sorry for the late answer ! I dont have an evidence of the response so well done on that small app ahah :)

Indeed, it would have been better with a specific code. 
I've seen better Google APIs, where they return a JSON body in which you could have been able to parse an error message  and a specific error "reason" better suited to be programmaticaly maniupulated. Error reasons would have been properly documented too...

I've been doing a little research on the subject and I came across those links :
https://developers.google.com/photos/library/reference/rest/v1/Status
https://cloud.google.com/apis/design/errors

Not sure if that can help you.

Thanks for your work in any case, gphotos-uploader-cli is of great use to me :)

**Comment by pacoorozco** [comment]
I've started the work to fix that. It's on the google-photos-api-client-go. I need to finish the tests.

**Comment by pacoorozco** [comment]
Fixed on v3.1.0

**Comment by mlbright** [comment]
hi @pacoorozco, the fix is not working with v3.4.0. I wonder if Google changed the error message for error code 429.

**Comment by pacoorozco** [comment]
Can you run the CLI when the quota is reached and using the debug flag? It will help to see what's the new message. Google changes the API wo/ announcement

**Comment by mlbright** [comment]
```
[info]   Found 38948 items to be uploaded processing location '/data'.
[debug]  Worker #1 processing: /data/2011/09/24/F1805E61-3450-4788-8B73-922CFA7A1FC3.jpeg
[debug]  New resumable upload for file [F1805E61-3450-4788-8B73-922CFA7A1FC3.jpeg].
[debug]  Current offset for [F1805E61-3450-4788-8B73-922CFA7A1FC3.jpeg] is 0.
[debug]  Resuming upload session for [F1805E61-3450-4788-8B73-922CFA7A1FC3.jpeg] starting at offset 0
[error]  Post "https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json": POST https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json giving up after 5 attempt(s)
Uploading files...   0% |                                       | (1/38948) [fail] X Error processing /data/2011/09/24/F1805E61-3450-4788-8B73-922CFA7A1FC3.jpeg
```

**Comment by mlbright** [comment]
There's a 429 error for exceeded requests per day, but also one for exceeded requests per minute. If the limit per day is exceed, the program should exit. If the limit per minute is exceeded, the program should  use the default retry strategy.
