### ISSUE TITLE
Lots of dbus sockets are left around when running headless

### ISSUE THREAD

**Issue by zotanmew** [gphotosuploader/gphotos-uploader-cli#297]
**Describe the bug**
Running as a cronjob leaves around one dbus process per execution, which ends up being adopted by init and stays around

**To Reproduce**
1. Set up cronjob
2. Log off (otherwise it uses the user dbus socket)
3. See error

**Expected behavior**
The socket should be either not created (storage backend file) or cleaned up on exit

**Screenshots**
<img src="https://img.zotan.services/i/34d26384b2c0493d5aa0d077f5da249b8eeb7de14aaf7a2f22dfc696832514ba.png">

**Desktop & Client versions (please complete the following information):**
 - Arch Linux (latest)
 - Version v3.0.1

**Comment by pacoorozco** [comment]
Use 'file' as Secrets Backed. Have you tried it?

**Comment by lhaus** [comment]
@pacoorozco as mentioned in the issue, that option is set in my config, yes

**Comment by pacoorozco** [comment]
Let me say that I have not tested it in headless setups. It was not my intention to run them in headless environments. 

Once said, it's strange that the `gphotos-uploader-cli` is using `dbus`. There is only one call to `dbus`, but this call is skipped if SecretsBackend is `file`.

For headless, you should probably be interested in rfgamaral/docker-gphotos-uploader who is using this CLI inside a docker.

**Comment by NorthernMan54** [comment]
FYI - In my setup running this headless I added a cleanup for this ( UID 1001 is the account that is running this )

```
#! /bin/sh

export GPHOTOS_CLI_TOKENSTORE_KEY=password

gphotos-uploader-cli --debug push | logger -t gphoto-upload-cli
pkill -u 1001 dbus-daemon
```
