### ISSUE TITLE
Upload files to albums with a certain order/sorting

### ISSUE THREAD

**Issue by eGit** [gphotosuploader/gphotos-uploader-cli#301]
**Is your feature request related to a problem? Please describe.**
I have the files video1, video2, video3, ..., video22, etc.

I want to upload them to Google Photos in this alphabetical order. Meaning, if I open the album, the first video should be video1, the second video2, and so on. The last video in the album should be video22

**Describe the solution you'd like**
In the config should be an option to upload in a certain order. Alphabetically for example. 

Probably it is then necessary to upload files one after the other (and not many files in parallel) to achieve ordering (or is this achievable using the Google Photos API - you probably know better).

**Comment by eGit** [comment]
Is nobody interested in this?

**Comment by pacoorozco** [comment]
The Google Photos API only allows to [order items at upload time](https://developers.google.com/photos/library/guides/upload-media#creating-media-item). 
I've modified the code to sort the files at upload time. Bear in mind that this order will only be maintained when:
- **the order is relative to the files you're uploading** 
- **the album is empty** (if you uploaded files previously, the new ones will be added to the end of the album)
- **the number of workers is 1** (see `--workers`)

**Comment by eGit** [comment]
In what version will this be available or should I build from source?

**Comment by pacoorozco** [comment]
It's available from the `v2.3.0`

**Comment by eGit** [comment]
> The Google Photos API only allows to [order items at upload time](https://developers.google.com/photos/library/guides/upload-media#creating-media-item). I've modified the code to sort the files at upload time. Bear in mind that this order will only be maintained when:
> 
> * **the order is relative to the files you're uploading**
> * **the album is empty** (if you uploaded files previously, the new ones will be added to the end of the album)
> * **the number of workers is 1** (see `--workers`)

Workers 1 seems to be the default. So no need to add it, right?

What happens if the download is interrupted? It will retry the same file again, or skip the failed file and therefore "destroy the upload ordering"? Can I set retries to infinite or interrupt gphotos-uploader-cli if there is an error?

**Comment by eGit** [comment]
Hi,

I now tested again with 3.3.1 but it is still not conserving the ordering of the files.

Test-Setup: Folder with videos:
sample-video1.mp4
sample-video2.mp4
sample-video3.mp4
sample-video4.mp4

gphotos-uploader-cli push --debug --workers 1 --config $DATA/software/my-config

Result. The order is not preserved. First sample-video2.mp4 is uploaded and it also has this order when I look in the album.

Here is some output from the test:

> [debug]  Upload file '/mnt/Data/test1/sample-video1.mp4' to album 'test1'.
[debug]  Upload file '/mnt/Data/test1/sample-video2.mp4' to album 'test1'.
[debug]  Upload file '/mnt/Data/test1/sample-video3.mp4' to album 'test1'.
[debug]  Upload file '/mnt/Data/test1/sample-video4.mp4' to album 'test1'.
[debug]  Upload file '/mnt/Data/test2/sample-video1.mp4' to album 'test2'.
[debug]  Upload file '/mnt/Data/test2/sample-video2.mp4' to album 'test2'.
[debug]  Upload file '/mnt/Data/test2/sample-video3.mp4' to album 'test2'.
[debug]  Upload file '/mnt/Data/test2/sample-video4.mp4' to album 'test2'.
[info]   Found 8 items to be uploaded processing location '/mnt/Data'.
[debug]  Worker #1 processing: /mnt/Data/test1/sample-video2.mp4
[debug]  New resumable upload for file [sample-video2.mp4].
[debug]  Current offset for [sample-video2.mp4] is 0.
[debug]  Resuming upload session for [sample-video2.mp4] starting at offset 0
[debug]  Worker #1 processing: /mnt/Data/test1/sample-video1.mp4
[debug]  New resumable upload for file [sample-video1.mp4].
Uploading files...  12% |██████████                                                                               | (1/8) [debug]  Successfully processing /mnt/Data/test1/sample-video2.mp4
[debug]  Current offset for [sample-video1.mp4] is 0.
[debug]  Resuming upload session for [sample-video1.mp4] starting at offset 0
[debug]  Worker #1 processing: /mnt/Data/test1/sample-video3.mp4                            
Uploading files...  25% |██████████████████████                                                                   | (2/8) [deb
