### ISSUE TITLE
Do we need to read the full file in order to detect already uploaded files?

### ISSUE THREAD

**Issue by mlangenberg** [gphotosuploader/gphotos-uploader-cli#303]
Today I ran `gphotos-uploader-cli` on a subfolder of my photo library. As expected around 3GB of photos were uploaded to Google Photos. 

When running `gphotos-uploader-cli` for a second time, this took longer than expected. I store all my photos on a network share and although already uploaded files were skipped from being uploaded again, the network activity seemed to indicate that each file was being fully read from the network share.

I am new to this project, so I'm not sure what design decisions were made in the past, but I would assume that comparing the file modification time to a timestamp in the local database would be sufficient for determining if a file should be skipped or uploaded again. Many backup utilities work that way.

My use case may be exceptional as most people will probably run this program where the data lives, but even in that case, doing a simple stat call is going to be much faster and efficient than reading the file into memory.

**Comment by pacoorozco** [comment]
Added since v3.2.0... Thanks a lot!
