### ISSUE TITLE
Auth on every push

### ISSUE THREAD

**Issue by stu1811** [gphotosuploader/gphotos-uploader-cli#310]
**Describe the bug**
Followed steps to setup the first time from readme. Authorize app the first time as expected. Now it's asking to authorize on every push. I expected to only authorize on the first push.

**To Reproduce**
1.  Add photos to directory
2. gphotos-uploader-cli push
3. auth through website
4. Repeat 1-3

**Expected behavior**
I expected to authorize the first time and not have to again

**Desktop & Client versions (please complete the following information):**
 - Operating System: Ubuntu 20,4
 - Version: gphotos-uploader-cli v3.2.0-4-gef047e3

```
{
  APIAppCredentials:
  {
    ClientID: REDACTED
    ClientSecret: REDACTED
  }
  Account: XXXXX@gmail.com
  SecretsBackendType: auto
  Jobs:
  [
    {
      SourceFolder: google_uploader
      CreateAlbums: folderName
      DeleteAfterUpload: false
      includePatterns: [ "*.jpg", "*.png" ]
      excludePatterns: [ "*ScreenShot*" ]    }
  ]
}
```

**Comment by pacoorozco** [comment]
Can you run the command with the `--debug` flag, please?

**Comment by stu1811** [comment]
```
:~$ gphotos-uploader-cli --debug push 
[info]   Reading configuration from '/home/stu/.gphotos-uploader-cli/config.hjson'
[debug]  Current configuration: {"APIAppCredentials":{"ClientID":"REDACTED","ClientSecret":"REMOVED"},"Account":"REDACTED@gmail.com","SecretsBackendType":"auto","Jobs":[{"SourceFolder":"/home/stu/google_uploader","CreateAlbums":"folderName","DeleteAfterUpload":false,"IncludePatterns":["*.jpg","*.png"],"ExcludePatterns":["*ScreenShot*"]}]}
[info]   Getting OAuth token for 'REDACTED@gmail.com'
[debug]  Unable to retrieve token from token manager: token was not found
[debug]  Getting OAuth2 token from prompt...

Visit the following URL in your browser:
```

**Comment by stu1811** [comment]
I got this to work tonight by logging in locally to my Ubuntu machine. Originally I was logging in over SSH. Any idea why it wouldn't work over SSH?

**Comment by pacoorozco** [comment]
Hi

Yes! The CLI is not intended to work in headless setup. One of the issues is that the `SecretsBackend: auto` is choosing  a backend that needs UI.

You can try setting this backend to `file` and see if that fix your problem.

**Comment by stu1811** [comment]
Setting `SecretsBackendType: file` fixed the problem. Maybe put something in the readme for remote users?
