### ISSUE TITLE
make ci fails

### ISSUE THREAD

**Issue by smontanaro** [gphotosuploader/gphotos-uploader-cli#313]
**Running `make ci` fails**

I'm a Go dummy, just cloned this repo to try uploading a bunch of photos. I installed the golang package (XUbuntu 20.04) and successfully ran `make build`, but `make ci` fails with this error:

```
% make ci
--> Running linter golangci v1.42.1...
internal/cmd/init_test.go:26:4: t.Cleanup undefined (type *testing.T has no field or method Cleanup) (typecheck)
	t.Cleanup(func() {
	  ^
make: *** [Makefile:77: lint] Error 1
```
As a Go-illiterate person I can't really offer much else in the way of input. 

**Desktop & Client versions:**
 - Operating System: Linux (XUbuntu 20.04)
 - Version gphotos-uploader-cli v3.2.1

**Comment by pacoorozco** [comment]
Hi @smontanaro 

I recommend you to follow the [Getting started](https://gphotosuploader.github.io/gphotos-uploader-cli/#/getting-started) steps in order to install the CLI.

**Comment by smontanaro** [comment]
@pacoorozco Thanks. I had no problem building the tool itself. I'm used to working from Git checkouts. It seemed to me though that there is something missing in either Make dependencies or underlying actions if in a naive checkout you can't run the unit tests.

**Comment by pacoorozco** [comment]
Hi @smontanaro 

Sorry for my previous answer, I though you wanted to install `gphotos-uploader-cli` in the easiest way. 

To follow up with your issue, can you share with me which `go` version are you using? It should work with go 1.16 and go 1.17.
