### ISSUE TITLE
Add ability to control bandwidth used

### ISSUE THREAD

**Issue by ricktonoli** [gphotosuploader/gphotos-uploader-cli#314]
**Is your feature request related to a problem? Please describe.**
Because my internet upload bandwidth is rather bad (2-4mb/s upload), when I synchronize photos it saturates the network and creates an overall bad experience for any other user or application on the network.

**Describe the solution you'd like**
I would like to be able to control the maximum upload bandwidth gphotos-uploader can use when sending files.

**Describe alternatives you've considered**
I've considered controlling that servers upload bandwidth at the local network level but that would impact all other services on the server.

**Comment by pacoorozco** [comment]
Hi @ricktonoli 

It's true that the `gphotos-uploader-cli` doesn't offer a way to control the bandwidth, but maybe you can reduce the impact in your network **by reducing the number of workers (`--workers`)**

I will let this issue opened in case that someone wants to work on it.
