### ISSUE TITLE
WSL Linux SecretsBackendType

### ISSUE THREAD

**Issue by syrm** [gphotosuploader/gphotos-uploader-cli#318]
**Describe the bug**
Cant get SecretsBackendType works on wsl linux cli headless.

I tried `SecretsBackendType: "file"`
I don't know what to put for the question « Enter the passphrase to open the token store »
so i let it empty, and i got the error : 
```After completing the authorization flow, enter the authorization code here: <obfuscated>
Enter the passphrase to open the token store:
panic: crypto/hmac: hash generation function does not produce unique values```

**Comment by pacoorozco** [comment]
Hi @syrm 
The token store is the file where your Google Photos tokens will be stored using a key as encryption. The passphrase should be the key to encrypt/decrypt this file. 

I suggest to try it again with a passphrase that is not empty. 

If it's still failing. Can you provide more data: Go version, gphotos-uploader cli version...

**Comment by syrm** [comment]
Even with a passphrase with 64 character i have the same error.
```
go version
go version go1.17.5 linux/amd64
```

```
gphotos-uploader-cli version
gphotos-uploader-cli v0.0.0
```

```
go install github.com/gphotosuploader/gphotos-uploader-cli@latest
```

**Comment by syrm** [comment]
I tried the v3.3.0 and building myself, and its work 👍

**Comment by pacoorozco** [comment]
I'm glad to see that the recommended way of installing the app is working. Thanks
