### ISSUE TITLE
Best way to run headless

### ISSUE THREAD

**Issue by Devenda** [gphotosuploader/gphotos-uploader-cli#320]
Having read all threads about running this headless I still have not found a solution.

Setting SecretsBackendType to auto or file still prompts me to enter a passphrase.
The fork of @rfgamaral is outdated and seems to no longer support the latest version.

How do I go about automating the upload? 

Thanks in advance!

**Comment by pacoorozco** [comment]
Hi @Devenda 

Unfortunately **this script was not intended to run in headless mode** (#311). 

Once you have completed the first run, obtaining the **authorization code** from Google Photos. The code is encrypted inside a file (if you're using `SecretsBackendType: file`) using the password (encryption key) that you provide.

Every time you run the CLI, you need to provide the same password to decrypt the file. You can provide it using a environment var (see it [here](https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration?id=gphotos_cli_tokenstore_key).

I hope this will help you to answer the question.

**Comment by Devenda** [comment]
Hi @pacoorozco,

Sorry, I must have not read the docs thoroughly!

This is exactly what I needed and it is working perfectly.

Many thanks and thank you for this project!
