### ISSUE TITLE
Google has deprecated the out-of-band authentication :-(

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#326]
**Describe the bug**
Google [has deprecated](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob) the out-of-band authentication that was used by this CLI. It has been deprecated since Feb 28, 2022. It means that new clients can't authenticate against Google :-(

**To Reproduce**
1. gphotos-uploader-cli
2. Go to the browser and copy the URL
3. See error

**Expected behavior**
The authentication should probably use _Loopback Ip Address._

**Screenshots**
![Screenshot_20220330_231527](https://user-images.githubusercontent.com/2443200/160932219-366156f0-e854-416b-ad70-8ffbc060abb6.png)

**Comment by mlangenberg** [comment]
Still working fine for me (using v3.2.1).

**Comment by pacoorozco** [comment]
@mlangenberg I've tried with the same version and It's not working for me 😓. Google says that the authentication method we are using is deprecated 🤷🏼
