### ISSUE TITLE
Unable to refresh the token, err: oauth2: cannot fetch token: 400 Bad Request

### ISSUE THREAD

**Issue by NorthernMan54** [gphotosuploader/gphotos-uploader-cli#331]
**Describe the bug**
Runs for about a week in headless mode ( with the environment variable), then stops working with this error message.  And if I manually go in and remove the `secrets` file, and run the auth process again it continues working.

As a complication in my setup, I'm running this on two different RPI's, to the same gphoto account, but I created 2 separate oauth credentials, and each RPI uses its own oauth credentials.  As the RPI's are in 2 separate houses, I can't tell if both are failing at roughly the same time, but it could be a factor.

Should I just run this into 2 separate gphoto accounts ? Any thoughts ?

```
gphotos-uploader-cli --debug push
[info]   Reading configuration from '/home/xxxxxx/.gphotos-uploader-cli/config.hjson'
[debug]  Current configuration: {"APIAppCredentials":{"ClientID":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","ClientSecret":"REMOVED"},"Account":"XXXXXXXXXXXXXXXXXXXXXXXXXX","SecretsBackendType":"file","Jobs":[{"SourceFolder":"/home/XXXXXXXXX/Desktop/gphoto","CreateAlbums":"folderName","DeleteAfterUpload":true,"IncludePatterns":[],"ExcludePatterns":[]}]}
[info]   Getting OAuth token for 'XXXXXXXXXXXXXXXXXXXXXXXXXX'
[debug]  Token has been expired, refreshing it...
[error]  Unable to refresh the token, err: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
[fatal]  unable to refresh the token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```

**Desktop & Client versions (please complete the following information):**
 - Operating System: **Linux - Raspbian GNU/Linux 10 (buster)**
 - Version:  **gphotos-uploader-cli v3.3.0-2-g470a20e**

**Comment by Devenda** [comment]
Same issue here.
In my case running push with a different passphrase and completing the auth fixes the issue until next time.

Given that the Google API pages looked quite different than mentioned in the guide, maybe some setting need to be changed on the Google side of things?

**Comment by NorthernMan54** [comment]
Well split my setup into 2 separate gphoto accounts today, will see what happens

**Comment by pacoorozco** [comment]
Hi! 
I'm running the CLI on Linux and it's working well. It can refresh the OAuth token without any problem. 

Let's try to troubleshoot the problem. Can you run `gphotos-uploader-cli version`?

I released recently a new version to adapt the CLI to the new OAuth flow I Google.

**Comment by Devenda** [comment]
I was on 3.3.1.

I just installed 3.4.0 and everything works great again.
I'll let you know if it stops working again!

(btw: does the new auth command need to be run when updating too? Because everything seems to run fine without doing so).

**Comment by Devenda** [comment]
Sadly, today the error returned, so it seems the token expires after 1 week.

**Comment by NorthernMan54** [comment]
Similar issue on my side after updating as well

**Comment by pacoorozco** [comment]
Please, the ones that the error is happening, can you update your comment with the output of the failing CLI with the debug flag enabled?

**Comment by NorthernMan54** [comment]
Sorry, this is a bit messy, as I’m logging this thru syslog

‘’’
May 10 06:15:34 walter gphoto-upload-cli: #033[0;1;36m[info]   #033[0mReading configuration from '/home/xxxxxx/.gphotos-uploader-cli/config.hjson'
May 10 06:15:34 walter gphoto-upload-cli: #033[0;1;32m[debug]  #033[0mCurrent configuration: {"APIAppCredentials":{"ClientID":"175591024665-3tj99kqv2926a5db5fdifjqg3qjf528f.apps.googleusercontent.com","ClientSecret":"REMOVED"},"Account":"xxxxxxxx @gmail.com","SecretsBackendType":"file","Jobs":[{"SourceFolder":"/home/xxxxxx/Desktop/gphoto","CreateAlbums":"folderName","DeleteAfterUpload":true,"IncludePatterns":[],"ExcludePatterns":[]}]}
May 10 06:15:34 walter gphoto-upload-cli: #033[0;1;36m[info]   #033[0mAuthenticating using token for 'xxxxxxxx@gmail.com'
May 10 06:15:35 walter gphoto-upload-cli: #033[0;1;31m[fatal]  #033[0moauth2: cannot fetch token: 400 Bad Request
May 10 06:15:35 walter gphoto-upload-cli: Response: {
May 10 06:15:35 walter gphoto-upload-cli:   "error": "invalid_grant",
May 10 06:15:35 walter gphoto-upload-cli:   "error_description": "Token has been expired or revoked."
May 10 06:15:35 walter gphoto-upload-cli: }
‘’’

**Comment by Devenda** [comment]
It seems to only log the config:

```root@omv:/# ./gphotos-uploader-cli --debug push
[info]   Reading configuration from '/root/.gphotos-uploader-cli/config.hjson'
[debug]  Current configuration: {"APIAppCredentials":{"ClientID":"291868308856-5ddrjvv9c45gsht7ce7u7apmv6f3fn6o.apps.googleusercontent.com","ClientSecret":"REMOVED"},"Account":"xxxxxxxx@gmail.com","SecretsBackendType":"auto","Jobs":[{"SourceFolder":"/Data/Photos","CreateAlbums":"Off","DeleteAfterUpload":false,"IncludePatterns":["**/*.jpg","**/*.JPG","**/*.png"],"ExcludePatterns":[]}]}
[info]   Authenticating using token for 'xxxxxxxx@gmail.com'
Enter the passphrase to open the token store:
[fatal]  oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```

**Comment by pacoorozco** [comment]
Hi all

After debugging a lot I've found the problem. Google put some restrictions to the access and refresh tokens that we use to authenticate our CLI.

You can read them [here](https://developers.google.com/identity/protocols/oauth2#expiration):
> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

So I don't see any other way to fix it different from running `gphotos-uploader-cli auth` each time that the refresh token is expired. 😪

**Comment by Devenda** [comment]
@pacoorozco This means that it is no longer possible to run headless?
What about setting it to an other status than 'testing'?

**Comment by pacoorozco** [comment]
This `gphotos-uploader-cli` needs an application running in the Google Cloud Platform under your user. It consumes quota from this application, which is created when you create the credentials the first time you run the CLI. 

So, **I don't think it's possible to pass the Google verification process** and offer this app for all the users from your Google account. [Read more here](https://support.google.com/cloud/answer/10311615?hl=en#zippy=%2Cexternal%2Cinternal%2Ctesting%2Cin-production)
