### ISSUE TITLE
Upload via enqueued jobs on the channel in parallel to the queueing process

### ISSUE THREAD

**Issue by wasserman** [gphotosuploader/gphotos-uploader-cli#334]
It seems that that adding each file (~ 40k in my case) to the queue is slow and an expensive operation, especially without anything consuming it until this stage is complete:

https://github.com/gphotosuploader/gphotos-uploader-cli/blob/b54651699f100150316403b98321dcdd92a59333/internal/cmd/push.go#L118

If consuming starts here then I think it would make sense to have this logic before, adapted in a way that it will consume in parallel to benefit from the channel use:
https://github.com/gphotosuploader/gphotos-uploader-cli/blob/b54651699f100150316403b98321dcdd92a59333/internal/cmd/push.go#L146

Thanks!

**Comment by pacoorozco** [comment]
Hi @wasserman 

https://github.com/gphotosuploader/gphotos-uploader-cli/blob/b54651699f100150316403b98321dcdd92a59333/internal/cmd/push.go#L118

Here you are queuing jobs to upload files. This queue is consumed by the workers:

https://github.com/gphotosuploader/gphotos-uploader-cli/blob/b54651699f100150316403b98321dcdd92a59333/internal/worker/queue.go#L90

By default is only one, but you can add more by setting their number, see `--workers`. 

So, queuing the files to be uploaded and the uploads of these files are happening in parallel. 🤷🏼 

Even though I've seen that given that the CLI doesn't start processing the upload results until enqueuing all the jobs, the results will not be shown to the user after a while. **But it's the Google API which will slow down the process, so I don't see the benefit of avoid this delay which is very small compare to the time to upload the files**. WDYT?
