### ISSUE TITLE
API hits 10k limit.  No idea if this is legit or a problem

### ISSUE THREAD

**Issue by wasserman** [gphotosuploader/gphotos-uploader-cli#335]
**Describe the bug**
I have a directory with about 500 folders/albums with about 40k photos total.  After uploading for about 1 hour it hits the 10k limit.

**To Reproduce**
1. Create directory with 500k folders with lots of photos spread across.
2. Inject debug for extra visibility at https://github.com/gphotosuploader/gphotos-uploader-cli/blob/b54651699f100150316403b98321dcdd92a59333/internal/cmd/push.go#L109
3. Eventually see something like this:
```
info]   Queueing folder AlbumX with 7 files.
[fail] X Unable to create album 'AlbumX': Post "https://photoslibrary.googleapis.com/v1/albums?alt=json": POST https://photoslibrary.googleapis.com/v1/albums?alt=json giving up after 5 attempt(s)
[info]   Queueing folder AlbumY with 57 files.
[fail] X Unable to create album 'AlbumY': Post "https://photoslibrary.googleapis.com/v1/albums?alt=json": POST https://photoslibrary.googleapis.com/v1/albums?alt=json giving up after 5 attempt(s)
```
Many folders were created that are empty on my Google Photos account.

**Expected behavior**
Failure and bailing with photos uploaded?   Understanding of what partially succeeded to know if I should continue my attempts regularly and will eventually complete the upload.

**Screenshots**
![image](https://user-images.githubusercontent.com/6733448/177198544-52d1ad1e-db78-4be0-bd36-ae139c093112.png)

**Desktop & Client versions (please complete the following information):**
 - Operating System: Ubuntu 21.10 under Windows 10 WSL
 - Version: Reports v0.0.0, but I compiled in a debug line.  Was cloned from master recently using https://gphotosuploader.github.io/gphotos-uploader-cli/#/getting-started?id=compiling-from-source
 

**Additional context**
Using config with `CreateAlbums: folderPath`

**Comment by wasserman** [comment]
Bump.  I was hoping to use this tool to bulk upload to my account from Linux.  Thanks!

**Comment by pacoorozco** [comment]
Hi @wasserman 

Sorry for the delay to answer you, the notification was left behind after a laptop replacement... 

Your question is documented [here](https://gphotosuploader.github.io/gphotos-uploader-cli/#/introduction?id=limitations). You can retry the `gphotos-uploader-cli` after the quota limitation of ~24 hours. **This is a rate limitation imposed by Google.**
