### ISSUE TITLE
Feedback: Great program

### ISSUE THREAD

**Issue by jdlail** [gphotosuploader/gphotos-uploader-cli#339]
Feedback from a non-programmer. 

This program has been extremely helpful to me. I have been manually tagging my photos and only want to upload the metadata-enhanced files to Google Photos. gphotos-uploader-cli  keeps track of file changes. A key is limiting the number of folders/files the program has to scan in a job. 

I'm using it in a Linux container on a Chromebook.

**Comment by pacoorozco** [comment]
Hi @jdlail 

I'm very glad to see that it has been helpful... 🙇🏼‍♂️ 

I would like to understand better two points from your message, just to check that I'm not misunderstanding it (non native English speaker here 😓 ) 

- What do you mean by _"manually tagging"_ the photos? What would be your expectation regarding _"upload the metadata-enhanced files"_? (EXIF?)
- Would _"limiting the number of folders"_ a feature that you would like to see in `gphotos-uploader-cli`? How would it looks like?

Thanks a lot for the feedback.

**Comment by jdlail** [comment]
_What do you mean by "manually tagging" the photos? What would be your expectation regarding "upload the metadata-enhanced files"? (EXIF?)_

Earlier this year, I started using Exiftool ([exiftool.org](url)) to manually tag photos with title/headline description/caption-abstract, keywords/subject, GPS for ones that didn't have it, etc. I rename them YYYY-MM-DD-hh-mm-ss-photo-name.jpg and organize them in folders by year and then a month sub folder (2022/2002-01, etc.) The goal is to use a portable filing system that works _good enough_ with more than one photo organizer or search program.

I was synching a NAS share to Google Photos with "Drive for Desktop" on an old Windows desktop and was duplicating a large number of files (I was changing the files enough that Google Photos did not see them as duplicates.) 

I decided to delete all my Google Photos and start over. (The Windows machine with "Google Drive for Desktop" was retired. I had turned off phone synching with Google Photos months earlier because of duplicates. I upload photos from my phone directly to my NAS.) There is no Google Drive for Desktop for ChromeOS and the Android Google Photos app won't sync a network folder.

So gphotos-uploader-cli is a perfect tool for uploading just the photos I have enhanced so far.  It created albums with the month folder name (2021-01, for example) and I can control what gets uploaded with include/exclude options/filters.

I hope that helps.

_Would "limiting the number of folders" a feature that you would like to see in gphotos-uploader-cli? How would it looks like?_

It might just be simpler to more strongly caution people to not set the "include pattern"/"exclude pattern" to include everything under the  "source folder" if there are hundreds of folders underneath with thousands of images.

I have some 27,000 photos in a lot of folders and did just that with some poor "include patterns" and "exclude patterns." I burned through the 10,000 daily requests to the Google API pretty quickly  (before I caught on to what was happening) while it was mostly looking at folders.

Limiting to a year folder and it's 12 subfolders for a job worked well the next day and now that I am caught up. I'm mostly doing a single folder (or multiple jobs of single folders) a day and using about 1% to 2% of my API requests per day. 

My guess is anything under 3,000 photos will not trigger the API 10,000 request limit.

Since it keeps track of what has been uploaded, I can run it against folders already uploaded when I discover new files that need to be in them and it only uploads those new additions. That granular control is awesome.

I use Google Photos for photo sharing, easy access from anywhere and as yet another backup copy of the photos stored on my NAS.

I hope my long-winded answer is helpful.

**Comment by pacoorozco** [comment]
Hi @jdlail 

Thanks a lot for your detailed answer... it's indeed really helpful and I'm going to pin it because it shows one of the use cases for what this CLI was done... 

Thanks 🥳
