### ISSUE TITLE
Date isn't preserved?

### ISSUE THREAD

**Issue by vsamoletov** [gphotosuploader/gphotos-uploader-cli#340]
**Describe the bug**
When I push my photos they're dated as now instead of the date stored in EXIF even if I see the correct date in the file's info.

**To Reproduce**
1. Set everything up as described in the official docs https://gphotosuploader.github.io/gphotos-uploader-cli/#/getting-started
2. Run ./gphotos-uploader-cli push
3. See your photos in Google Photos

**Expected behavior**
All my uploaded photos dated with the date they were taken

**Desktop & Client versions (please complete the following information):**
 - Operating System: MacOS 13.0.1 (22A400) (Ventura)
 - Version gphotos-uploader-cli 3.4.0

**Comment by vsamoletov** [comment]
<img width="512" alt="Screenshot 2022-12-03 at 9 36 28 PM" src="https://user-images.githubusercontent.com/214931/205471346-0bddbc6b-1be9-4777-99f1-bc27a410b4d1.png">
![Screenshot 2022-12-03 at 9 35 26 PM](https://user-images.githubusercontent.com/214931/205471375-3bfc06e1-890e-47cd-96cd-804fbe41065c.jpeg)

**Comment by pacoorozco** [comment]
Hi folk!

Would you be so kind to send me the EXIF information of your image? O even better the image itself? I've been testing and if the image contain the creation date as EXIF data, it is preserved.

**Comment by pacoorozco** [comment]
Hi @vsamoletov 

Do you have any update?
