### ISSUE TITLE
How to use pre-existing credential and token ?

### ISSUE THREAD

**Issue by khurshid-alam** [gphotosuploader/gphotos-uploader-cli#343]
I alreday have cliet_id, client_secret, access_token, refresh_token from another app. I want to use that with this so that I can upload to same album.

How do I achieve that ? I am using file backend on linux. (please allow a empty password so that it can be used in script, but thats a seperate issue)

I would love to have that feature .  

Thanks.

**Comment by pacoorozco** [comment]
You can configure `gpohotos-uploader-cli` with your `client_id` and `client_secret`. The `access_token` and `refresh_token` expire every now and them, so you will need to authenticate accordingly.
