### ISSUE TITLE
What is the best way to update to the latest version?

### ISSUE THREAD

**Issue by jdlail** [gphotosuploader/gphotos-uploader-cli#344]
What is the best way to update to the latest version?

Do you have to authorize with Google again or will it use the existing credentials?

**Comment by pacoorozco** [comment]
All versions are backward compatible, so you should just update the binary (depending how you have installed it) and the new version will read the configuration file. Let me know if you see any problem with it.

**Comment by jdlail** [comment]
Thanks!
