### ISSUE TITLE
Upload Errors Occur Intermittently

### ISSUE THREAD

**Issue by ufolux** [gphotosuploader/gphotos-uploader-cli#345]
**Describe the bug**
I'm trying to upload my images from an SD card to Google Photos using `gphotos-uploader-cli push`. At first everything worked fine when uploading, but after uploading about 100-300 images, all the upload requests started to fail with errors, and here are the error messages

```
[error]  Post "https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json": POST https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json giving up after 5 attempt(s)
Uploading files...   0% |                                                       | (1/4286) [fail] X Error processing /Volumes/EOS_DIGITAL/DCIM/100CANON/9K2A2563.CR3
```
When I terminate the program and restart the upload, the error continues to occur. But when I wait about 1 hour and retry again, everything is back to normal until the same error happens again after uploading 100-300 images.

**Expected behavior**
No errors should occur until the quota is reached.

**Desktop & Client versions (please complete the following information):**
 - Operating System: mac
 - Version: gphotos-uploader-cli 3.5.0

**Comment by pacoorozco** [comment]
Hi @ufolux 

Based on the error, the CLI is failing when trying to create the media item in Google Photos (just after the upload).

It seems you're trying to upload *raw photos*. I don't have a lot of experience on it, so *[have you read if your Canon is a supported one?](https://support.google.com/photos/answer/6193313?hl=en#zippy=%2Ctypes-of-raw-files-you-can-back-up)*

**Comment by ufolux** [comment]
> Hi @ufolux
> 
> Based on the error, the CLI is failing when trying to create the media item in Google Photos (just after the upload).
> 
> It seems you're trying to upload _raw photos_. I don't have a lot of experience on it, so **[have you read if your Canon is a supported one?](https://support.google.com/photos/answer/6193313?hl=en#zippy=%2Ctypes-of-raw-files-you-can-back-up)**

Thank you for replying. Sure, my Canon is R6 which is supported by Google Photos, and when I manually upload them it works well. As for `raw`, I was also trying to upload some JPG photos, but still got the same error:

```
l] X Error processing /Volumes/Untitled/DCIM/100MSDCF/DSC00361.JPG
Uploading files...  40% |███████████████████                              | (28/69)
```

I had to stop the program and try several times to upload all the photos.

Hope this can be helpful.

**Comment by pacoorozco** [comment]
Hi @ufolux 

Thanks a lot to continue sharing feedback.. I've just created a new version enabling more details about the error. **Would you be so kind to update to `v3.5.1-alpha`  and run again the CLI?** 

https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v3.5.1-alpha

**Comment by ufolux** [comment]
> Hi @ufolux
> 
> Thanks a lot to continue sharing feedback.. I've just created a new version enabling more details about the error. **Would you be so kind to update to `v3.5.1-alpha` and run again the CLI?**
> 
> https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v3.5.1-alpha

Thank you for your reply! I have tried v3.5.1-alpha version with these parameters:
```
gphotos-uploader-cli push --workers 10 --debug
```
The error looks like this:

```
[error]  Post "https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json": POST https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json giving up after 5 attempt(s)
[error]  Post "https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json": POST https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json giving up after 5 attempt(s)
Uploading files...  99% |██████████████████████████████████████ | (455/457) [fail] X Error processing /Volumes/EOS_DIGITAL/DCIM/100CANON/9K2A8287.CR3
Uploading files...  99% |██████████████████████████████████████ | (456/457) [fail] X Error processing /Volumes/EOS_DIGITAL/DCIM/100CANON/9K2A8289.CR3
[error]  Post "https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json": POST https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json giving up after 5 attempt(s)
Uploading files... 100% |███████████████████████████████████████| (457/457) [fail] X Error processing /Volumes/EOS_DIGITAL/DCIM/100CANON/9K2A8288.CR3
[done] √ 457 processed files: 172 successfully, 285 with errors```

**Comment by VRspace4** [comment]
I've had the same issue for years and using the latest versions.

**Comment by pacoorozco** [comment]
Hi folks!

I've just released a [new version of the CLI](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v4.0.0-alpha). **It implements a lot of non-backwards compatible changes**, but I believe it can help to identify the problem you had in the past. 

**Would you mind to tried?**
