### ISSUE TITLE
Unable to run latest version

### ISSUE THREAD

**Issue by jdlail** [gphotosuploader/gphotos-uploader-cli#353]
I tried to update from 3.5.0 to the latest version using the script on the documentation site, but ran into an issue.

I used this method of installing the latest version:

```
LOCATION=$(curl -s https://api.github.com/repos/gphotosuploader/gphotos-uploader-cli/releases/latest \
| grep browser_download_url \
| awk '{ print $2 }' \
| tr -d \" \
| grep linux); wget --quiet -O - $LOCATION | tar -zxf -
```
After running, I got the below error in trying to use it.

```
 ~/packages/photo-uploader/gphotos-uploader-cli push
/home/jacklail/packages/photo-uploader/gphotos-uploader-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/jacklail/packages/photo-uploader/gphotos-uploader-cli)
/home/jacklail/packages/photo-uploader/gphotos-uploader-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/jacklail/packages/photo-uploader/gphotos-uploader-cli)
```
I am on Debian 11 Bullseye.

I was able to use a backup file to revert to the old version (and it is working), but is a way to resolve this?

Thank you for any guidance you might be able to provide.

**Comment by jdlail** [comment]
Additional info.

Running  apt install  libc6

gives this message:

`libc6 is already the newest version (2.31-13+deb11u6).`

**Comment by pacoorozco** [comment]
Hi @jdlail 

I don't think it is related to the `gphotos-uploader-cli` by itself. It seems that you're using an old version of the `libc6`, which is not compatible with the generated binary. 

One way to fix that is upgrading the `libc6` to a newer version (>2.32) or you can build your `gphotos-uploader-cli` binary following [these instructions](https://gphotosuploader.github.io/gphotos-uploader-cli/#/getting-started?id=compiling-from-source).

**Can you confirm that it works from the compiled version?**

**Comment by jdlail** [comment]
Hi Paco:

Just an update. I did upgrade from Debian Bullseye (11) to Debian Bookworm (12) and was able to update gphotos-uploader-cli  with no issues.

**Comment by pacoorozco** [comment]
I'm happy to hear it @jdlail . Thanks for the update.
