### ISSUE TITLE
Add option to specify web port for authentication

### ISSUE THREAD

**Issue by benze** [gphotosuploader/gphotos-uploader-cli#370]
During the auth flow, a random port is used to complete the authentication process.

In order to use a Docker container, there must be a way to know apriori the port that will be used.

Can an additional parameter be added to specify a known port to use instead?

**Comment by pacoorozco** [comment]
The challenges to use this CLI in a docker are several, but let me add this option to make it easier. I'm working on the v4 which will have several improvements and new features, let me added to it.
