### ISSUE TITLE
Photos "uploaded" but not showing up in google photos

### ISSUE THREAD

**Issue by PabloRomanH** [gphotosuploader/gphotos-uploader-cli#372]
After uploading a bunch of fotos without any error messages, nothing shows up in my photo library.
All these are photos that had once been in my library but that I deleted to make space. Now I got google One so I want to upload them again. I wonder if Photos remembers that I previously had them and deleted them and considers them duplicates so it won't let them be added to the library again.

I'm using 4.0.0-alpha-02 on a Mac, installed with brew.
I uploaded around 150GB of photos over two days, reaching the maximum quota once, so it looks like at least the data was sent to google photos.

**Comment by Sloth-on-meth** [comment]
same issue here

**Comment by pacoorozco** [comment]
I'm afraid that this should be something to address to the Google Photos support team. 

**Have you tried to list the items using the `gphotos-uploader-cli list media-items` command?**
