### ISSUE TITLE
Add a cli switch to specify the name of the album

### ISSUE THREAD

**Issue by milosgajdos** [gphotosuploader/gphotos-uploader-cli#393]
First of all thanks for a very handy tool.

**Is your feature request related to a problem? Please describe.**
I find it mildly annoying that I need to specify the name of the album via some elaborate way of changing a physical file.

**Describe the solution you'd like**
I'd love if there was a cli switch that lets me specify the name of the album to be created in google photos or the one that already exists
```
gphotos-uploade-cli push --album "Foobar"
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pacoorozco** [comment]
Hi @milosgajdos 

It makes sense, instead of a CLI switch I'll add it to the configuration file, in the Jobs definition. In that way would be compatible with multiple Jobs definitions.

I'm going to work on it. Thanks a lot for the suggestion and feedback 🤗
