### ISSUE TITLE
Uploads are showing date of upload as filename.

### ISSUE THREAD

**Issue by mikebilly** [gphotosuploader/gphotos-uploader-cli#398]
Photos: Photo's names are named like ``2023-10-23.jpg`` which is the day of upload, which is wrong, instead of their original filenames like ``PXL_20231003_125152999.jpg``

Videos: Video's names are named like photos, the date of upload. Some video info is not shown.

![photos](https://github.com/gphotosuploader/gphotos-uploader-cli/assets/29500216/d6018100-20d1-4952-820b-e11761260982)

**Comment by pacoorozco** [comment]
Hi @mikebilly 

Good catch! **Can I ask how you have found this header `X-Goog-Upload-Name`?** Is there any documentation regarding it?

I tried to follow [this Google documentation](https://developers.google.com/photos/library/guides/upload-media), where It doesn't know anything about the `X-Goog-Upload-Name`. 

Thanks for submitting the bug and the fix 😍

**Comment by pacoorozco** [comment]
I've found that the [PHP library provided by Google](https://github.com/google/php-photoslibrary/blob/99d03c959561a24e9613fa1c3d77086c64575846/src/Google/Photos/Library/V1/PhotosLibraryClient.php#L150) use the header `X-Goog-Upload-File-Name`, even it says that it's not longer recommended
