### ISSUE TITLE
allow custom RedirectURLHostname 

### ISSUE THREAD

**Issue by mikebilly** [gphotosuploader/gphotos-uploader-cli#402]
I'm running headless, so I need to tunnel localhost to a different domain. I'd request a feature to use --redirect to specify a custom ``RedirectURLHostname``. 

``RedirectURLHostname`` is declared at https://github.com/int128/oauth2cli/blob/master/oauth2cli.go#L58

So in ``internal/oauth/oauth.go`` at https://github.com/gphotosuploader/gphotos-uploader-cli/blob/main/internal/oauth/oauth.go#L26, we can declare a new property:
```
type Config struct {
	// OAuth's application ID.
	ClientID string
	// OAuth's application secret.
	ClientSecret string

	// Logger function for debug.
	Logf func(format string, args ...interface{})

	// Port to bind the local authenticator
	Port int

	oAuth2Config *oauth2.Config

	RedirectURLHostname string
}
```

and also in ``internal/oauth/oauth.go`` modify like this:
```
func (c *Config) getTokenFromWeb(ctx context.Context) (*oauth2.Token, error) {
	ready := make(chan string, 1)
	localServerBindAddress := fmt.Sprintf("127.0.0.1:%d", 80)
	cfg := oauth2cli.Config{
		OAuth2Config:           *c.oAuth2Config,
		LocalServerReadyChan:   ready,
		Logf:                   c.Logf,
		LocalServerBindAddress: []string{localServerBindAddress},
		RedirectURLHostname: c.RedirectURLHostname,
	}
```

and in ``internal/app/oauth.go`` modify like this:
```
func (app *App) AuthenticateFromWeb(ctx context.Context, port int) (*http.Client, error) {
	account := app.Config.Account
	app.Logger.Infof("Getting authentication token for '%s'", account)

	cfg := &oauth.Config{
		ClientID:     app.Config.APIAppCredentials.ClientID,
		ClientSecret: app.Config.APIAppCredentials.ClientSecret,
		Logf:         app.Logger.Debugf,
		Port:         port,
		RedirectURLHostname: "the specified URL redirect link",
	}
```

**Comment by pacoorozco** [comment]
You can test the branch `issue-402` or the tagged [version 4.2.0-rc1](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v4.2.0-rc1)

Tell me if it works fine, because I've not found how to implement proper tests 😓
