### ISSUE TITLE
Show Google Photos API error description to make easier the troubleshooting

### ISSUE THREAD

**Issue by mikebilly** [gphotosuploader/gphotos-uploader-cli#405]
I was uploading normally but suddenly got a lot of errors like this, which prevented me from uploading further photos and videos:
```
[fail] X Error processing /content/drive/MyDrive/Manh content/9_10_2923/DCIM/Camera/20231008_001958.mp4: creating media items: Post "https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json": POST https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json giving up after 4 attempt(s)
```

I tried redoing init, redoing auth, resetting everything but I still got those errors. Few days a go I was able to upload thousands photos and videos which were around 1tb, everything was uploaded without errors, today I was uploading around 400 photos and videos which were only 60gb and it got lots of error processing.

**Comment by pacoorozco** [comment]
**Did you run the `gphotos-uploader-cli` using the `--debug` flag?** I would expect that using it you will be able to see the Google Photos API messages. 

Check the [quota limits that Google Photos API publish](https://developers.google.com/photos/library/guides/api-limits-quotas), AFAIK you're hitting one of them.

**Comment by pacoorozco** [comment]
I'll review why the Google Photos API error is not shown. Based on your previous message `Quota exceeded for quota 'concurrent write request' of service 'photoslibrary.googleapis.com'` points exactly to a quota limit reach at Google Photos API. 

You can see it in your Google Photos API console (hopefully) or just rely on the error message that you shared

**Comment by pacoorozco** [comment]
It could be, I don't know how Google has implemented this quota, maybe it's by IP address, by Google Photos account, by Google Cloud Project or a permutation of them... 🤷🏼

**Comment by pacoorozco** [comment]
So, the problem was not `gphotos-uploader-cli` which retried the error three times (given it was a retrievable error) and then gave up in order to not be blocked. The change I will do is to show the description of the Google Photos API errors in order to make easier the troubleshooting.

It's probably a regression, because it should be shown when using `--debug`  but it seems it's not. 🙇🏼
