### ISSUE TITLE
4.2.0 doesn't show version

### ISSUE THREAD

**Issue by tbm** [gphotosuploader/gphotos-uploader-cli#413]
**Describe the bug**
`version` doesn't show the correct version:
```
./gphotos-uploader-cli version
gphotos-uploader-cli Version: 0.0.0-git
```

This should say 4.2.0

**To Reproduce**
1. Download gphotos-uploader-cli_4.2.0_linux_amd64.tar.gz from GitHub
2. Unpack
3. run `./gphotos-uploader-cli version`

**Expected behavior**
In the past we had:
```
gphotos-uploader-cli 3.4.0
```

**Desktop & Client versions (please complete the following information):**
 - Operating System: Linux
 - Version 4.2.0

**Comment by pacoorozco** [comment]
Hi @tbm 

Thanks for raising this bug. It has been affected since the release of version 4.x ( commit: fc634f10fa6fd42a8ad9cce6a7364245a02752d2)

**Comment by tbm** [comment]
Thanks!
