### ISSUE TITLE
"option CreateAlbums is invalid, '⏎" on fresh installation

### ISSUE THREAD

**Issue by zeograd** [gphotosuploader/gphotos-uploader-cli#416]
**Describe the bug**
After configuration the OAuth token, account and folder in a fresh installation, the "auth" subcommand fails with the error message: `Error occurred: invalid configuration at '/home/olivier/.gphotos-uploader-cli/config.hjson': option CreateAlbums is invalid, '⏎`

**To Reproduce**
1. Install release 4.2.1 for linux from release page
2. Run `gphotos-uploader-cli init`
3. Follow the instruction in https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration to setup ClientID, ClientSecret, Account and Jobs[0].SourceFolder
4. Run `gphotos-uploader-cli auth`

**Expected behavior**
The authentication step should be trigerred

**Desktop & Client versions (please complete the following information):**
 - Operating System: linux debian 12.0 amd64
 - Version: 4.2.1

**Additional context**
Anonymized config.hjson file is

```
{
  APIAppCredentials: {
    ClientID: xxxxxxxxxxxxxx.apps.googleusercontent.com
    ClientSecret: yyyyyyyyyyyyyyyyyyyyy
  }
  Account: zzzzzzzz@gmail.com
  SecretsBackendType: file
  Jobs: [
    {
      SourceFolder: xxxxxxxxx
      DeleteAfterUpload: true
      IncludePatterns: []
      ExcludePatterns: []
    }
  ]
}


```

**Comment by zeograd** [comment]
After tweaking, it seems like `CreateAlbums: Off` added as part of Jobs[0] did the trick.

**Comment by pacoorozco** [comment]
Yes, the `CreateAlbums` is required... I'll update the documentation or I'll make it optional and assign a default value. 

Thanks for raising the bug.
