### ISSUE TITLE
Pre resize/encode video to lower resolution and quality before upload

### ISSUE THREAD

**Issue by WACKYprog** [gphotosuploader/gphotos-uploader-cli#427]
**Is your feature request related to a problem? Please describe.**
The issue pertains to the cost of Google Photos. I use Google Photos as secondary storage only (for its search capabilities) and would like to upload pictures and videos at a lower quality.

**Describe the solution you'd like**
I propose using the ffmpeg and imagick CLI tools to pre-resize/encode videos to lower resolution and quality before uploading.

- For images, we will provide an option to specify the number of megapixels and quality.
- For videos, users can choose the number of lines (e.g., 780p) and quality.

**Describe alternatives you've considered**
I currently have my own simple Go app that runs pre-encoding and stores the files in the upload folder. After that, the gphotos-uploader-cli is executed.

**Additional context**
- ffmpeg and imagick CLI will become dependencies for the gphotos-uploader-cli; however, they will only be required if the user configures the job to resize/encode. They will not be dependencies during build time. This can be mitigated with docker .

- The local file will not be affected, and we will use a temporary folder to store encoded files.

- If you believe the feature is a good idea for the project, I'm more than happy to implement it.

**Comment by pacoorozco** [comment]
I'm sorry to admit that this far from where this CLI in intended to be used. The idea of the CLI is just deal with Google Photos and it doesn't prepare files to be uploaded in advance.

As you have already said, you can prepare them before and then use this CLI to just upload the file. 

> Let's do one thing, only one, but let's do it well :-D

Thanks anyways for the suggestion.

**Comment by WACKYprog** [comment]
@pacoorozco Totally makes sense and sort of expected the answer.  

As I sad I do have go app to do that already. But I don't love the setup :)

If I would have some way to specific for a given job a pre process CLI command.  

something like that:
`
    {
      SourceFolder: YOUR_FOLDER_PATH
      Album: "auto:folderName"
      DeleteAfterUpload: false
      IncludePatterns: [ "**/*.jpg", "**/*.png" ]
      ExcludePatterns: [ "**/ScreenShot*" ]
      PreProcess: 'convert  -resize 1000000@\ %infile -o %outfile '
    }
`
 I did went over some other wontfix from the past and look like there is some interest in this kind capabilities  For example: #133,  #10.
 
 Let me me know if you think this kind of solution would be acceptable with in a frame of "Let's do one thing".
