### ISSUE TITLE
cannot upload a video that's more than 20gb

### ISSUE THREAD

**Issue by mikebilly** [gphotosuploader/gphotos-uploader-cli#452]
I'm getting:
[error]  Failed to resume upload: googleapi: got HTTP response code 413 with body: {
  "code": 3,
  "message": "The request exceeded the max file size limit of 20 GB."
}
[fail] X Error processing /content/drive/MyDrive/Upload/8_4_2024/DCIM/mcpro24fps/V240407-162152-30fps-1_30-iso75-tmc_auto_0.mp4: resuming upload: resuming upload: googleapi: got HTTP response code 413 with body: {
  "code": 3,
  "message": "The request exceeded the max file size limit of 20 GB."
}

My video is 22.8gb

**Comment by pacoorozco** [comment]
Hi!

This is a limitation of the Google Photos service. You can read it [here](https://support.google.com/photos/answer/6193313?hl=en&co=GENIE.Platform%3DDesktop&sjid=480504685198924847-EU#zippy=%2Cwhat-you-need-to-back-up-photos-videos), where it refers to a maximum 10GB file size, while the error message in the HTTP request says 20GB. Unfortunately, we can't do anything to change that value.
