### ISSUE TITLE
Is there any way to divide the job as smaller parts? Because Google api limits 10000 each day

### ISSUE THREAD

**Issue by kiang** [gphotosuploader/gphotos-uploader-cli#453]
**Is your feature request related to a problem? Please describe.**
I have about 80000 photos to upload to google photo. But I found each time I execute the push command, gphotos-uploader-cli just try to upload files from the beginning.

**Describe the solution you'd like**
I can find logs in .gphotos-uploader-cli/uploaded_files. But have no idea how to let gphotos-uploader-cli not trying to upload duplicated photos.

**Describe alternatives you've considered**
Or if it's possible to define the task as file, I can try to generate lists for each task.

**Comment by pacoorozco** [comment]
The CLI should keep track of the already uploaded photos. It's stored in a DB inside the `~/.gphotos-uploader-cli` folder.

You can run the CLI with the `--debug` flag to see if there's any problem

**Comment by jdlail** [comment]
I limit pushes to a folder and do one folder at a time.

`     SourceFolder: /path/to/photos
      Album: "template:%_directory%"
      DeleteAfterUpload: false
      IncludePatterns: ["**/2024-05/**"]`

**Comment by pacoorozco** [comment]
Hi

Thanks for using the cli. It's up to you how to do it. You can continue
uploading folder by folder or just wait until quota is granted again.CLI
will continue where it was left before
