### ISSUE TITLE
Handling Modified Files

### ISSUE THREAD

**Issue by aaroneden** [gphotosuploader/gphotos-uploader-cli#471]
**Is your feature request related to a problem? Please describe.**
I use my NAS as  the source of truth for my photos and Gphotos as a way to share my photos with family members living at home with my and on our Google Home devices.   I frequently use Lightroom to do touch-ups on the photos on my NAS.

**Describe the solution you'd like**

I would love a way to be able to have files that are modified locally:
1. Move the old version of the photo in Gphotos to a configurable Album ("Delete Me")
2. Re-upload the modified photo to Google Photos

**Describe alternatives you've considered**
Use the patch or addEnrichment functionality to effectively "tag" photos that have been updated locally and should be deleted in gPhotos by the user manually.

**Additional context**
None

**Comment by pacoorozco** [comment]
The Google Photos API doesn't allow us to modify albums/photos that were not uploaded by this CLI.

**Comment by aaroneden** [comment]
That's fine.

**Comment by pacoorozco** [comment]
Id say that this is already documented: https://gphotosuploader.github.io/gphotos-uploader-cli/#/introduction?id=albums
