### ISSUE TITLE
Configurations docs don't explain "no album" option

### ISSUE THREAD

**Issue by StephenFluin** [gphotosuploader/gphotos-uploader-cli#480]
**Describe the bug**
I'm moving from 'CreateAlbums: Off' to the new Album setting, but it's unclear how to make no albums?

**To Reproduce**
Visit https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration
Look for how to not make albums

**Expected behavior**
An example is provided

--
Love the project by the way! Keep up the amazing work! This tool has single-handedly kept me in the Google Photos ecosystem with 13TB of photos and videos!

**Comment by pacoorozco** [comment]
Hi @StephenFluin 

I've to admit that the documentation can say it more clearly, so I'll probably update it.

To not create albums, just remove the `Album` parameter in your configuration.

**Comment by StephenFluin** [comment]
Here's my config with the deprecated option removed (and no Album), and it errors. When I specify an Album or the deprecated option it works.

```

{
  APIAppCredentials: {
    ClientID:     "<hidden>"
    ClientSecret: "<hidden>"
  }
  Account: "<hidden>"
  SecretsBackendType: "auto"
  Jobs: [
    {
      SourceFolder: "/staging/"
      DeleteAfterUpload: false
      IncludePatterns: ["**/*.jpg","**/*.JPG","**/*.mp4", "**/*.MP4", "**/*.360", "**/*.HIF"]
	    ExcludePatterns: ["**/*.THM","**/*.LRV"]
    }
  ]
}
```

With error
```
[info]   Reading configuration from '/home/stephen/.gphotos-uploader-cli/config.hjson'
Error: invalid configuration at '/home/stephen/.gphotos-uploader-cli/config.hjson': option CreateAlbums is invalid, '
Usage:
  gphotos-uploader-cli push [flags]
```

**Comment by StephenFluin** [comment]
@pacoorozco Any chance we can re-open this such excluding "albums" fails?

**Comment by pacoorozco** [comment]
Hi

Are you using the latest version? Have you just removed the Albums parameter as is explained here: https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration?id=album

Let me know if that fixes the problem

Aquel que planta árboles bajo los que sabe
muy bien que nunca se sentará, ha descubierto
el auténtico significado de la vida.

-------- Mensaje original --------
El 3/12/24 22:33, Stephen Fluin  ha escrito:
