### ISSUE TITLE
 failed storing token

### ISSUE THREAD

**Issue by chris-y** [gphotosuploader/gphotos-uploader-cli#52]
Error: `failed storing token: failed storing token into keyring: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'`

The cause seems to be that gnome-keyring doesn't work on my system.

Looking at https://github.com/nmrshll/gphotos-uploader-cli/issues/15 there appears to be some work on using a different keystore if dbus isn't running.  dbus is running here, so maybe some way to force that might be the answer?

Otherwise, it looks like https://github.com/99designs/keyring supports more backends, including encrypted files, and might be more flexible?  Also may resolve https://github.com/nmrshll/gphotos-uploader-cli/issues/51 given that it also supports wincred.

**Comment by pacoorozco** [comment]
Hi @chris-y 

Can you test if it's working? PR #71 should have fixed it

Paco

**Comment by chris-y** [comment]
Hello

I'm slightly scuppered by the fact that without https://github.com/nmrshll/oauth2-noserver/pull/4 I can't complete the authentication, and I'm not sure how to re-add my patch under the new buildsystem.

(Frankly I'm amazed that anybody can pass the token part currently as the browser being open blocks the server that it is trying to connect to, so it shouldn't work for anybody!)

Any chance you can get that patch merged in?  I can give it another go then and hopefully get this issue closed too.

Chris

**Comment by pacoorozco** [comment]
@chris-y I can not merge the PR (I don't have rights) but I can use the current code to auth my client. **Can you do it?**

**Comment by chris-y** [comment]
No, because the process handing the callback is the same as the one launching the browser, so it never listens until the browser is closed, which is too late.

**Comment by chris-y** [comment]
As this is now in it's own organisation, maybe https://github.com/nmrshll/oauth2-noserver can be forked here?  There are lots of pull requests which could be merged in then.

**Comment by pacoorozco** [comment]
Hi @chris-y 

I'm thinking to do it, there are a lot of issues related with it... but... the current version `v0.6.0` should work. Please test it, I've been testing it and it works fine... If something it's not working I'd like to know it to improve the testing system.

**Comment by chris-y** [comment]
Same unfortunately.  Browser just sits waiting for a connection that doesn't exist until it is shut down:
![image](https://user-images.githubusercontent.com/1818803/63536139-df682500-c50a-11e9-99b0-62222bb997fb.png)
The console shows the blue text whilst the browser is open, and the text below after it is shut down:
![image](https://user-images.githubusercontent.com/1818803/63536198-0161a780-c50b-11e9-98fe-ce4703b24301.png)

**Comment by pacoorozco** [comment]
@chris-y Check my last answer on #123

**Comment by chris-y** [comment]
As far as I'm aware my settings are correct.

**Comment by pacoorozco** [comment]
@chris-y The logs that you are showing in the previous image are not shown in the last version of the client.

**Are you using a binary or a compiled one?** 
**Can you run `gphotos-uploader-cli version` and publish the version that you're using?**

**Comment by chris-y** [comment]
Self-compiled.  I've updated again, deleted and recreated the application as per the documentation, and everything is now working. Yay!  Thank you!
