### ISSUE TITLE
Can't install uploader via snap

### ISSUE THREAD

**Issue by Densol92** [gphotosuploader/gphotos-uploader-cli#56]
According to https://github.com/nmrshll/gphotos-uploader-cli/blob/master/.docs/installation.md
gphotos-uploader-cli can be installed via snapcraft but:
```bash
sudo snap install gphotos-uploader-cli
error: snap "gphotos-uploader-cli" not found
```

**Comment by pacoorozco** [comment]
I'm afraid that we are not publishing any on `snap`. The documentation is updated but this PR #35 has not been merged...

**Comment by pacoorozco** [comment]
We're having problems to publish `gphotos-uploader-cli`. It seems that the snap name is reserved by someone else :-(

Working to solve it... use [binaries](https://github.com/nmrshll/gphotos-uploader-cli/releases/latest) instead.
