### ISSUE TITLE
Token missing after manual oauth

### ISSUE THREAD

**Issue by goldcove** [gphotosuploader/gphotos-uploader-cli#57]
I'm running gphotos-uploader-cli on a headless server and the manual oauth fails after I manually curl the reply URL from google.

```
2019/05/17 20:15:53 Failed to open browser, you MUST do the manual process.
2019/05/17 20:15:54 Authentication will be cancelled in 120 seconds
oauthoauthConfig.Exchange() failed with 'oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_request",
  "error_description": "Missing required parameter: code"
}'
```

Tried installing gnome-keyring but with that did not help.

**Comment by zhangyangjing** [comment]
I have the same error too, with manually curl URL.

**Comment by pacoorozco** [comment]
We are not currently supporting **headless usage**. We would like it, so contributions are welcomed :-D
