### ISSUE TITLE
2019/05/26 01:14:55 Rate limit reached, sleeping for 10 seconds...

### ISSUE THREAD

**Issue by poleguy** [gphotosuploader/gphotos-uploader-cli#61]
Is google putting the smack down on this uploader, or is this just me?
2019/05/26 01:14:55 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:15:05 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:15:16 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:15:26 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:15:36 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:15:46 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:15:56 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:16:06 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:16:16 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:16:26 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:16:36 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:16:46 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:16:56 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:17:06 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:17:17 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:17:27 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:17:37 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:17:47 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:17:57 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:18:07 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:18:17 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:18:27 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:18:37 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:18:47 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:18:57 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:19:07 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:19:17 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:19:27 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:19:37 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:19:47 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:19:57 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:20:08 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:20:18 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:20:28 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:20:38 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:20:48 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:20:58 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:21:08 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:21:18 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:21:28 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:21:38 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:21:48 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:21:58 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:22:08 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:22:18 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:22:28 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:22:38 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:22:48 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:22:59 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:23:09 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:23:19 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:23:29 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:23:39 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:23:49 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:23:59 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:24:09 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:24:19 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:24:29 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:24:39 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:24:49 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:24:59 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:25:09 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:25:19 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:25:30 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:25:40 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:25:50 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:26:00 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:26:10 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:26:20 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:26:30 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:26:40 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:26:50 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:27:00 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:27:10 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:27:20 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:27:30 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:27:40 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:27:50 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:28:00 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:28:10 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:28:20 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:28:31 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:28:41 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:28:51 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:29:01 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:29:11 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:29:21 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:29:31 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:29:41 Rate limit reached, sleeping for 10 seconds...
2019/05/26 01:29:51 Rate limit reached, sleeping for 10 seconds...

**Comment by Eerovil** [comment]
Create your own App in Google Console and use the given app credentials

**Comment by Tra2x** [comment]
By the way, I would recommend, to expand the sleeping time to 60 seconds.
Because on page [https://developers.google.com/photos/library/guides/best-practices](url) it's mentioned, that the client should wait 30 seconds.

> For 429errors, the client may retry with minimum 30 s delay. For all other errors, retry may not be applicable. Ensure your request is idempotent and see the error message for guidance.

And with this client 5 threads are running in parallel, so my advise is to expand it to 60 seconds. When I made this change I had the feeling that I do not get to much errors anymore.

**Comment by pacoorozco** [comment]
This should be addressed at https://github.com/gphotosuploader/google-photos-api-client-go/issues/8. It's this package which is responsible of it.
